// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.xberg.Xberg;
import dev.xberg.EmbeddingConfig;
import dev.xberg.ExtractionConfig;
import java.util.Optional;
import dev.xberg.JsonUtil;

/** E2e tests for category: embed_extra. */
public class EmbedExtraTest {

    @Test
    void testEmbedTextsBatch() throws Exception {
        // Batch embed texts
        var config = JsonUtil.fromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}", EmbeddingConfig.class);

        var result = Xberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"Hello\"", String.class), JsonUtil.fromJson("\"World\"", String.class)), config);


    }

}
