{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kreuzberg.fullname" . }}-cache
  labels:
    {{- include "kreuzberg.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- $storageClass := .Values.persistence.storageClass | default .Values.global.storageClass -}}
  {{- if $storageClass }}
  {{- if (eq "-" $storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
