// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a47e9403195e17eb96c9fb33571662840df1e41fa5876c49414e2103ea80a7af
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		setupFiles: ["./setup.ts"],
	},
});
