# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eac1990079bd5bdd7be5353a7455a762fe5ebd7dfbd5d3d32a2f537c8479ce03
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
