# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Kreuzberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Kreuzberg.list_embedding_backends()
    end
  end
end
