# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6edec774a1773f53048f6c6b6b0d5840b647b56a2d24fcc10c8073b97d5adc88
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Kreuzberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Kreuzberg.list_embedding_backends()
    end
  end
end
