# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: language
defmodule E2e.LanguageTest do
  use ExUnit.Case, async: true

  describe "lang_detect_config" do
    test "Language detection with specific language config" do
      {:ok, result} = Kreuzberg.extract_file_sync("semantic/mixed_topics.txt", %{"language_detection" => %{"enabled" => true, "languages" => ["en", "de", "fr"]}})
    end
  end

  describe "lang_detect_english" do
    test "Language detection works on English text" do
      {:ok, result} = Kreuzberg.extract_file_sync("semantic/mixed_topics.txt", %{"language_detection" => %{"enabled" => true}})
    end
  end
end
