# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a21487ee16a8ac19abc71fd0da8956ae1ef5539c7bbd5132eebdf71412a00229
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Kreuzberg.clear_post_processors()
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Kreuzberg.list_post_processors()
    end
  end
end
