# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4a1ba67a4f5c1df8960273cbf70ae5a0b3e4484d660587af29d0365a2685180
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_document_extractors" do
    test "list_document_extractors" do
      result = Kreuzberg.list_document_extractors()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Kreuzberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Kreuzberg.list_post_processors()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Kreuzberg.list_validators()
    end
  end
end
