# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_document_extractors" do
    test "list_document_extractors" do
      result = Kreuzberg.list_document_extractors()
    end
  end

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Kreuzberg.list_embedding_backends()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Kreuzberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Kreuzberg.list_post_processors()
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Kreuzberg.list_renderers()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Kreuzberg.list_validators()
    end
  end
end
