# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff70a0fb20bb8a85befa7146cc6f50aa50e503f35ce8470dcb9f88ad77457009
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: render
defmodule E2e.RenderTest do
  use ExUnit.Case, async: true

  describe "render_custom_dpi" do
    test "Render PDF page with custom DPI" do
      {:ok, result} = Kreuzberg.render_pdf_page_to_png("pdf/tiny.pdf")
      assert result.is_png == true
      assert result.byte_length >= 50
    end
  end

  describe "render_high_dpi" do
    test "Render PDF page with high DPI setting (300 DPI)" do
      {:ok, result} = Kreuzberg.render_pdf_page_to_png("pdf/fake_memo.pdf", %{"dpi" => 300})
    end
  end

  describe "render_iterator" do
    test "Iterate all PDF pages as PNG images" do
      {:ok, result} = Kreuzberg.render_pdf_page_to_png("pdf/tiny.pdf")
      assert result.is_png == true
      assert result.page_count >= 1
    end
  end

  describe "render_multi_page" do
    test "Render a page from a multi-page PDF document" do
      {:ok, result} = Kreuzberg.render_pdf_page_to_png("pdf/a_brief_introduction_to_neural_networks_neuronalenetze_en_zeta2_2col_dkrieselcom.pdf")
      assert String.length(result.result) >= 1000
    end
  end

  describe "render_output_djot" do
    test "Extract PDF with Djot output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "djot"})
      assert String.trim(result.output_format) == "djot"
      assert String.length(result.content) >= 10
    end
  end

  describe "render_output_html" do
    test "Extract PDF with HTML output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "html"})
      assert String.trim(result.output_format) == "html"
      assert Enum.any?(["<", ">", "</"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "render_output_markdown" do
    test "Extract PDF with Markdown output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "markdown"})
      assert String.trim(result.output_format) == "markdown"
      assert Enum.any?(["\#", "**", "*"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "render_output_plain" do
    test "Extract PDF with plain text output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "plain"})
      assert String.trim(result.output_format) == "plain"
      assert String.length(result.content) >= 50
    end
  end

  describe "render_single_page" do
    test "Render a single PDF page to PNG" do
      {:ok, result} = Kreuzberg.render_pdf_page_to_png("pdf/tiny.pdf")
      assert result.is_png == true
      assert result.byte_length >= 100
    end
  end
end
