# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Kreuzberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Kreuzberg.list_renderers()
    end
  end
end
