# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:411f5f833163f073c882dd19dd4fb115a1d5d49636d1356157f3ac978ab1eefe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      result = Xberg.clear_reranker_backends()
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Xberg.list_reranker_backends()
    end
  end
end
