# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0e6bfdc493dbb3039a011ec2dd5858d0f4b3ea1b3d382aa04a397f265dcc913
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: text_processing
defmodule E2e.TextProcessingTest do
  use ExUnit.Case, async: true

  describe "text_clean_extracted" do
    test "Extract and clean text content from document" do
      {:ok, result} = Kreuzberg.extract_file_sync("json/simple.json")
      assert String.length(result.content) >= 5
    end
  end

  describe "text_normalize_whitespace" do
    test "Extract text with whitespace normalization (no consecutive spaces)" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf")
      refute String.contains?(to_string(result.content), "  ")
    end
  end
end
