// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:56004f51a78d993aeb6a6ded9db21f6e3c6ec78975762409765a4879e621972c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: async.</summary>
public class AsyncTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractBytes()
    {
        // Async extract_bytes call on PDF document
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractBytesEmptyMime()
    {
        // extract_bytes empty MIME async
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractBytesInvalidMime()
    {
        // extract_bytes unsupported MIME async
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractFile()
    {
        // Async extract_file call on PDF document
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractFileDocx()
    {
        // Async extract_file call on DOCX document
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractFileHtml()
    {
        // Async extract_file call on HTML document
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractFileImage()
    {
        // Async extract_file call on image document
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_AsyncExtractFileWithConfig()
    {
        // Async extract_file call with output format and chunking config
    }
}
