// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dd93473087b96456bc6144a489cc3729ce636d5375b091a410cf408811fbb003
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: image.</summary>
public class ImageTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_ImageMetadataOnly()
    {
        // JPEG image to validate metadata extraction without OCR.
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_ImageSvgBasic()
    {
        // SVG image extraction.
    }
}
