// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: ocr_backend_management.</summary>
public class OcrBackendManagementTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_OcrBackendsClear()
    {
        // Clear all OCR backends and verify list is empty
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.True(string.IsNullOrEmpty(result.Result?.ToString()));
    }

    [Fact]
    public void Test_OcrBackendsList()
    {
        // List all registered OCR backends
        var result = Kreuzberg.ListOcrBackends(null);
    }

    [Fact]
    public async Task Test_OcrBackendsUnregister()
    {
        // Unregister nonexistent OCR backend gracefully
        var result = await Kreuzberg.ExtractFile("", null, null);
    }
}
