// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a21487ee16a8ac19abc71fd0da8956ae1ef5539c7bbd5132eebdf71412a00229
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: ocr_backend_management.</summary>
    public class OcrBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_OcrBackendsClear()
        {
            // Clear all OCR backends and verify list is empty
            KreuzbergLib.ClearOcrBackends();
        }

        [Fact]
        public void Test_OcrBackendsList()
        {
            // List all registered OCR backends
            var result = KreuzbergLib.ListOcrBackends();

        }

        [Fact]
        public void Test_OcrBackendsUnregister()
        {
            // Unregister nonexistent OCR backend gracefully
            KreuzbergLib.UnregisterOcrBackend("nonexistent-backend-xyz");
        }


    }
}
