// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d01be624990c7d52bcd711630db07de9501daff5c3c503473ce881d8113937f1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: text_processing.</summary>
public class TextProcessingTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "TODO: implement C# e2e tests via the spikard C# binding API")]
    public void Test_TextCleanExtracted()
    {
        // Extract and clean text content from document
    }

    [Fact(Skip = "TODO: implement C# e2e tests via the spikard C# binding API")]
    public void Test_TextNormalizeWhitespace()
    {
        // Extract text with whitespace normalization (no consecutive spaces)
    }
}
