// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78357c7d3461a89b496c648e59bea66167c656f8df54e7c7da37c4674ffbd3c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: xml.</summary>
public class XmlTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_XmlPlantCatalog()
    {
        // XML plant catalog to validate streaming XML extraction.
    }
}
