// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: document_extractor_management

use kreuzberg::{clear_document_extractors, list_document_extractors};

#[test]
fn test_document_extractors_clear() {
    // Clear all document extractors and verify list is empty
    let _ = clear_document_extractors();
}

#[test]
fn test_extractors_list() {
    // List all registered document extractors
    let _ = list_document_extractors();
}
