// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df949a23ed01418d22789527e8549214dbbbfc9722e5d867b5312dbc59a47aff
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: document_extractor_management

use kreuzberg::{clear_document_extractors, list_document_extractors};

#[test]
fn test_document_extractors_clear() {
    // Clear all document extractors and verify list is empty
    let _ = clear_document_extractors();
}

#[test]
fn test_extractors_list() {
    // List all registered document extractors
    let _ = list_document_extractors();
}
