// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: embed_extra

use kreuzberg::normalize;

#[test]
fn test_embed_normalize_unit() {
    // Normalize unit vector
    let data_json = serde_json::json!([1.0, 0.0, 0.0]);
    let data = serde_json::from_value(data_json).unwrap();
    let _ = normalize(&data);
}

#[test]
fn test_embed_normalize_zero() {
    // Normalize zero vector
    let data_json = serde_json::json!([0.0, 0.0, 0.0]);
    let data = serde_json::from_value(data_json).unwrap();
    let _ = normalize(&data);
}
