// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3a6dda560f25c8fdfe33e34727b5abb0de5d04b9fe91ab6cb16b1cc3655037ce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: registry

use kreuzberg::{list_document_extractors, list_ocr_backends, list_post_processors, list_validators};

#[test]
fn test_list_document_extractors() {
    // List document extractors
    let _ = list_document_extractors();
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends();
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors();
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators();
}
