// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: uri

use kreuzberg::classify_uri;

#[test]
fn test_classify_uri_anchor() {
    // Classify fragment URI
    let url = r#"#section-header"#;
    let _ = classify_uri(&url);
}

#[test]
fn test_classify_uri_email() {
    // Classify mailto URI
    let url = r#"mailto:user@example.com"#;
    let _ = classify_uri(&url);
}

#[test]
fn test_classify_uri_https() {
    // Classify HTTPS URL
    let url = r#"https://example.com/page"#;
    let _ = classify_uri(&url);
}
