# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocxMetadata do
  @moduledoc """
  Word document metadata.

  Extracted from DOCX files using shared Office Open XML metadata extraction.
  Integrates with `office_metadata` module for core/app/custom properties.
  """

  @typedoc "Word document metadata."
  @type t :: %__MODULE__{
          core_properties: map() | nil,
          app_properties: map() | nil,
          custom_properties: map() | nil
        }

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
