# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3e9750349b7aeaefee4dc21b4616209b660931a3204927feb49e14ec77cbd152
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          text: String.t() | nil,
          metadata: map()
        }

  defstruct element_type: :title,
            text: nil,
            metadata: nil
end
