# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3e9750349b7aeaefee4dc21b4616209b660931a3204927feb49e14ec77cbd152
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()]
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: []
end
