# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.StructuredInput do
  @moduledoc """
  Signals consumed by the call-mode heuristic.

  All fields derive from a prior xberg extraction — no double-work.
  This is a plain DTO; it intentionally has no dependency on internal
  xberg extraction types so it can be constructed from any source.
  """

  @typedoc "Signals consumed by the call-mode heuristic."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          page_count: non_neg_integer(),
          text_coverage: float(),
          avg_chars_per_page: float(),
          embedded_image_count: non_neg_integer(),
          user_force_vision: boolean()
        }

  defstruct mime_type: nil,
            page_count: 0,
            text_coverage: 0.0,
            avg_chars_per_page: 0.0,
            embedded_image_count: 0,
            user_force_vision: false
end
