<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: cache_operations. */
final class CacheOperationsTest extends TestCase
{
    /** Generate cache key from file path, MIME type, and version */
    public function test_cache_key_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::generate_cache_key("[\"file.pdf\",\"application/pdf\",\"v1\"]");
        $this->assertGreaterThanOrEqual(10, strlen($result->result));
    }

    /** Generate cache key from single part */
    public function test_cache_key_single(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::generate_cache_key("[\"test\"]");
    }

    /** Validate empty cache key (should return false but not error) */
    public function test_cache_key_validate_empty(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::validate_cache_key("");
    }

    /** Validate a valid cache key format */
    public function test_cache_key_validate_valid(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::validate_cache_key("abc123def456");
    }
}
