<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:87b418d5c76eb4f617bd08fea183f904aedfb33db6e2e8a14c84867477e631c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: embed_extra. */
final class EmbedExtraTest extends TestCase
{
    /** Normalize unit vector */
    public function test_embed_normalize_unit(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::normalize([1.0, 0.0, 0.0]);
    }

    /** Normalize zero vector */
    public function test_embed_normalize_zero(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::normalize([0.0, 0.0, 0.0]);
    }
}
