<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:917f8aaede1d331052b6de5b9ba05bb05d49b1e63f5bf7280b1583f0146456af
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: keywords. */
final class KeywordsTest extends TestCase
{
    /** Tests keyword extraction using RAKE algorithm */
    public function test_keywords_rake(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("pdf/fake_memo.pdf", ["keywords" => ["algorithm" => "rake", "max_keywords" => 10]]);
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10, strlen($result->content));
        $this->assertNotEmpty($result->keywords);
        $this->assertGreaterThanOrEqual(1, count($result->keywords));
        $this->assertLessThanOrEqual(10, $result->keywords_count);
    }

    /** Tests keyword extraction using YAKE algorithm */
    public function test_keywords_yake(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("pdf/fake_memo.pdf", ["keywords" => ["algorithm" => "yake", "max_keywords" => 10]]);
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10, strlen($result->content));
        $this->assertNotEmpty($result->keywords);
        $this->assertGreaterThanOrEqual(1, count($result->keywords));
        $this->assertLessThanOrEqual(10, $result->keywords_count);
    }
}
