<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: language. */
final class LanguageTest extends TestCase
{
    /** Language detection with specific language config */
    public function test_lang_detect_config(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extract_file_sync("semantic/mixed_topics.txt", ["language_detection" => ["enabled" => true, "languages" => ["en", "de", "fr"]]]);
    }

    /** Language detection works on English text */
    public function test_lang_detect_english(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extract_file_sync("semantic/mixed_topics.txt", ["language_detection" => ["enabled" => true]]);
    }
}
