<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: ocr_backend_management. */
final class OcrBackendManagementTest extends TestCase
{

    /** Clear all OCR backends and verify list is empty */
    public function test_ocr_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearOcrBackends();


    }


    /** List all registered OCR backends */
    public function test_ocr_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listOcrBackends();


    }


    /** Unregister nonexistent OCR backend gracefully */
    public function test_ocr_backends_unregister(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::unregisterOcrBackend("nonexistent-backend-xyz");


    }

}
