<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: ocr_backend_management. */
final class OcrBackendManagementTest extends TestCase
{

    /** Clear all OCR backends and verify list is empty */
    public function test_ocr_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearOcrBackends();


    }


    /** List all registered OCR backends */
    public function test_ocr_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listOcrBackends();


    }


    /** Unregister nonexistent OCR backend gracefully */
    public function test_ocr_backends_unregister(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::unregisterOcrBackend("nonexistent-backend-xyz");


    }

}
