<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: pdf. */
final class PdfTest extends TestCase
{

    /** render_pdf_page_to_png: first page */
    public function test_render_pdf_page_first(): void
    {
        $pdf_bytesBytes = file_get_contents("pdf/fake_memo.pdf");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: pdf/fake_memo.pdf"); }
        $result = Xberg::renderPdfPageToPng($pdf_bytesBytes, 0);

            $this->assertGreaterThanOrEqual(100, strlen($result));


    }


    /** render_pdf_page_to_png: page out of range */
    public function test_render_pdf_page_out_of_range(): void
    {
        $this->expectException(\Exception::class);        $pdf_bytesBytes = file_get_contents("pdf/fake_memo.pdf");
        if ($pdf_bytesBytes === false) { $this->fail("failed to read fixture: pdf/fake_memo.pdf"); }
        Xberg::renderPdfPageToPng($pdf_bytesBytes, 999);
    }

}
