<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{
    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile_async("");
    }

    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::list_post_processors();
    }
}
