<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:411f5f833163f073c882dd19dd4fb115a1d5d49636d1356157f3ac978ab1eefe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: registry. */
final class RegistryTest extends TestCase
{

    /** List embedding backends */
    public function test_list_embedding_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listEmbeddingBackends();


    }


    /** List OCR backends */
    public function test_list_ocr_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listOcrBackends();


    }


    /** List post-processors */
    public function test_list_post_processors(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listPostProcessors();


    }


    /** List renderers */
    public function test_list_renderers(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listRenderers();


    }


    /** List validators */
    public function test_list_validators(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listValidators();


    }

}
