<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a1aae9fb2958c8dbcf1e5a2ea1796cf9695239739764269d7b6311ec452495e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: registry_operations. */
final class RegistryOperationsTest extends TestCase
{
    /** Get file extensions for DOCX MIME type */
    public function test_extensions_docx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    }

    /** Get file extensions for HTML MIME type */
    public function test_extensions_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("text/html");
    }

    /** Get file extensions for PDF MIME type */
    public function test_extensions_pdf(): void
    {
        $result = Kreuzberg::getExtensionsForMime("application/pdf");
        $this->assertContains("pdf", $result);
    }
}
