<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a21487ee16a8ac19abc71fd0da8956ae1ef5539c7bbd5132eebdf71412a00229
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{

    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearRenderers();


    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRenderers();


    }

}
