<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: text_processing. */
final class TextProcessingTest extends TestCase
{
    /** Extract and clean text content from document */
    public function test_text_clean_extracted(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("json/simple.json");
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
    }

    /** Extract text with whitespace normalization (no consecutive spaces) */
    public function test_text_normalize_whitespace(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("pdf/fake_memo.pdf");
        $this->assertStringNotContainsString("  ", $result->content);
    }
}
