<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: xml. */
final class XmlTest extends TestCase
{
    /** XML plant catalog to validate streaming XML extraction. */
    public function test_xml_plant_catalog(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async("xml/plant_catalog.xml");
        $this->assertEquals("application/xml", $result->mime_type);
        $this->assertGreaterThanOrEqual(100, strlen($result->content));
    }
}
