// Generated by alef. Do not edit by hand.
// alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/**
 * PowerPoint presentation metadata.
 *
 * Extracted from PPTX files containing slide counts and presentation details.
 */
data class PptxMetadata(
    /** Total number of slides in the presentation */
    val slideCount: Int = 0,
    /** Names of slides (if available) */
    val slideNames: List<String> = emptyList(),
    /** Number of embedded images */
    val imageCount: Int? = null,
    /** Number of tables */
    val tableCount: Int? = null,
)
