// Generated by alef. Do not edit by hand.
// alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** One QR code decoded from an extracted image. */
data class QrCode(
    /** Decoded payload (text, URL, vCard string, …). */
    val payload: String,
    /**
     * Detector-reported confidence in `[0.0, 1.0]`. `null` when the decoder
     * does not expose confidence (the default `rqrr` backend always reports
     * `Some` because successful decode implies high confidence).
     */
    val confidence: Float? = null,
    /**
     * Bounding box of the QR code inside the source image, in pixel coordinates
     * (`x`, `y` of the top-left corner; `width`, `height` of the rectangle).
     * `null` if the decoder did not report a bounding box.
     */
    val bbox: QrBoundingBox? = null,
)
