// Generated by alef. Do not edit by hand.
// alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** Configuration for the summarisation post-processor. */
data class SummarizationConfig(
    /** Summarisation strategy. */
    val strategy: SummaryStrategy = SummaryStrategy.EXTRACTIVE,
    /** Maximum summary length in tokens. `null` lets the backend pick a default. */
    val maxTokens: Int? = null,
    /**
     * LLM configuration for the abstractive backend. Ignored when
     * `strategy = Extractive`. Required when `strategy = Abstractive`.
     */
    val llm: LlmConfig? = null,
)
