# frozen_string_literal: true

source "https://rubygems.org"

gem "rspec", "~> 3.12"
gem "kreuzberg", path: "../../packages/ruby"
gem "rubocop", "~> 1.66"
gem "rubocop-performance", "~> 1.21"
gem "rubocop-rspec", "~> 3.0"
