// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bbc5e80596d2ac5012a7c21e99dc37c3d191d8700e1e08d01e969a1b88018c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right.
/// </summary>
public sealed class BBox
{
    [JsonPropertyName("x1")]
    public float X1 { get; set; } = 0.0f;

    [JsonPropertyName("y1")]
    public float Y1 { get; set; } = 0.0f;

    [JsonPropertyName("x2")]
    public float X2 { get; set; } = 0.0f;

    [JsonPropertyName("y2")]
    public float Y2 { get; set; } = 0.0f;

}
