// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:423e7923485d66a45c541f6aa1131dd0bf4133712f215075cf3a3d9b376fd99a
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
