// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
