// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:faeab5c29a474378e5b5a57a283ce5cca951123947278b1afd6c31fcc45384c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// JATS contributor with role.
/// </summary>
public sealed class ContributorRole
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("role")]
    public string? Role { get; set; } = null;

}
