// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d9324873dcdebff893fa0a9d663f02cac4c4749616cabd4c9c1f2a9ab3a3154
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE (DBF) file metadata.
/// </summary>
public sealed class DbfMetadata
{
    [JsonPropertyName("record_count")]
    public ulong RecordCount { get; set; } = 0;

    [JsonPropertyName("field_count")]
    public ulong FieldCount { get; set; } = 0;

    [JsonPropertyName("fields")]
    public List<DbfFieldInfo> Fields { get; set; } = [];

}
