// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:123e3bffe035ac54c07fd6e78bbcbd0add2e2cd881d406c1df6b0e86d7075763
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of DOC text extraction.
/// </summary>
public sealed class DocExtractionResult
{
    /// <summary>
    /// Extracted text content. Aliased as `text` for back-compat.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    /// <summary>
    /// Document metadata.
    /// </summary>
    [JsonPropertyName("metadata")]
    public DocMetadata Metadata { get; set; } = default!;

}
