// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6576b3af9cf7dd85d7db1a13f2a5ca82463240a1bb388d1ee04fd0cf70f8425f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// EPUB metadata (Dublin Core extensions).
/// </summary>
public sealed class EpubMetadata
{
    [JsonPropertyName("coverage")]
    public string? Coverage { get; set; } = null;

    [JsonPropertyName("dc_format")]
    public string? DcFormat { get; set; } = null;

    [JsonPropertyName("relation")]
    public string? Relation { get; set; } = null;

    [JsonPropertyName("source")]
    public string? Source { get; set; } = null;

    [JsonPropertyName("dc_type")]
    public string? DcType { get; set; } = null;

    [JsonPropertyName("cover_image")]
    public string? CoverImage { get; set; } = null;

}
