// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aa6861c6300961c816cbe467125c9e17c8fe818ad78ed3b639932456c14fbc82
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// How the extracted text was produced.
/// </summary>
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native,
    [JsonPropertyName("ocr")]
    Ocr,
    [JsonPropertyName("mixed")]
    Mixed,
}
