// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:89d3b1f10857dd448ca834466dd342528bbe47d6ebe9530a8b43c842c128322a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Extracted inline image with metadata.
/// </summary>
public sealed class ExtractedInlineImage
{
    /// <summary>
    /// Uses `bytes::Bytes` for cheap cloning of large buffers.
    /// </summary>
    [JsonPropertyName("data")]
    public byte[] Data { get; set; } = Array.Empty<byte>();

    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    [JsonPropertyName("filename")]
    public string? Filename { get; set; } = null;

    [JsonPropertyName("description")]
    public string? Description { get; set; } = null;

    [JsonPropertyName("dimensions")]
    public List<uint>? Dimensions { get; set; } = null;

    [JsonPropertyName("attributes")]
    public List<string> Attributes { get; set; } = [];

}
