// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// FictionBook (FB2) metadata.
/// </summary>
public sealed class FictionBookMetadata
{
    [JsonPropertyName("genres")]
    public List<string> Genres { get; set; } = [];

    [JsonPropertyName("sequences")]
    public List<string> Sequences { get; set; } = [];

    [JsonPropertyName("annotation")]
    public string? Annotation { get; set; } = null;

}
