// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(FracTypeJsonConverter))]
public enum FracType
{
    [JsonPropertyName("bar")]
    Bar,
    [JsonPropertyName("nobar")]
    NoBar,
    [JsonPropertyName("linear")]
    Linear,
    [JsonPropertyName("skewed")]
    Skewed,
}


/// <summary>
/// Custom JSON converter for <see cref="FracType"/> that respects explicit variant names.
/// </summary>
internal sealed class FracTypeJsonConverter : JsonConverter<FracType>
{
    public override FracType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "bar" => FracType.Bar,
            "nobar" => FracType.NoBar,
            "linear" => FracType.Linear,
            "skewed" => FracType.Skewed,
            _ => throw new JsonException($"Unknown FracType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, FracType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            FracType.Bar => "bar",
            FracType.NoBar => "nobar",
            FracType.Linear => "linear",
            FracType.Skewed => "skewed",
            _ => throw new JsonException($"Unknown FracType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
