// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d310f8ce95aa319f1d976a5eb0d747c10f81bcb608b17c21934660f50b41bfea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Image element metadata.
/// </summary>
public sealed class ImageMetadataType
{
    /// <summary>
    /// Image source (URL, data URI, or SVG content)
    /// </summary>
    [JsonPropertyName("src")]
    public string Src { get; set; } = "";

    /// <summary>
    /// Alternative text from alt attribute
    /// </summary>
    [JsonPropertyName("alt")]
    public string? Alt { get; set; } = null;

    /// <summary>
    /// Title attribute
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; } = null;

    /// <summary>
    /// Image dimensions as (width, height) if available
    /// </summary>
    [JsonPropertyName("dimensions")]
    public List<uint>? Dimensions { get; set; } = null;

    /// <summary>
    /// Image type classification
    /// </summary>
    [JsonConverter(typeof(ImageTypeJsonConverter))]
    [JsonPropertyName("image_type")]
    public ImageType ImageType { get; set; } = default!;

    /// <summary>
    /// Additional attributes as key-value pairs
    /// </summary>
    [JsonPropertyName("attributes")]
    public List<string> Attributes { get; set; } = [];

}
