// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5a15bdc00fde7bd8ece80aa8385d7510c29a1bd415f7917b339a24861d57f8eb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Link type classification.
/// </summary>
public enum LinkType
{
    /// <summary>
    /// Anchor link (#section)
    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,
    /// <summary>
    /// Internal link (same domain)
    /// </summary>
    [JsonPropertyName("internal")]
    Internal,
    /// <summary>
    /// External link (different domain)
    /// </summary>
    [JsonPropertyName("external")]
    External,
    /// <summary>
    /// Email link (mailto:)
    /// </summary>
    [JsonPropertyName("email")]
    Email,
    /// <summary>
    /// Phone link (tel:)
    /// </summary>
    [JsonPropertyName("phone")]
    Phone,
    /// <summary>
    /// Other link type
    /// </summary>
    [JsonPropertyName("other")]
    Other,
}
