// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : KreuzbergException
{
    public LoadErrorException(string message) : base(message) { }

    public LoadErrorException(string message, Exception innerException) : base(message, innerException) { }
}
