// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0621c79d34a1c0d020c112c2bd1758873839480096425f6a90edc553b8dd58d1
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
