// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0888b7d3074d8c5ff7ec0c10e23119cac8000b6c77da01a7a1d87e2e9eb28906
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
