// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8def7157124398fe13f9579eae2d652373b455f0d0ef700691cb986e8ace4a4c
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
