// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c14b10edfc7b8e9a7b1943d087208dedf8cfac3768d9575ae60ec55d1c52ba69
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
