// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b00dfb8c12aef4f8ae416e8515d5844f8e602e585f6c554edd30f65606a43f92
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
