// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:967e144c67407b9bc8ea7490bcab22792aa24ef81e86941f8ba94eee1551107b
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
