// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fe637f97705a6d08a3853fad1e66f0d0c954c67e9ae2cbc2e3aba8e764c0356e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Multi-backend OCR pipeline with quality-based fallback.
///
/// Backends are tried in priority order (highest first). After each backend
/// produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
/// the result is accepted. Otherwise the next backend is tried.
/// </summary>
public sealed class OcrPipelineConfig
{
    /// <summary>
    /// Ordered list of backends to try. Sorted by priority (descending) at runtime.
    /// </summary>
    [JsonPropertyName("stages")]
    public List<OcrPipelineStage> Stages { get; set; } = [];

    /// <summary>
    /// Quality thresholds for deciding whether to accept a result or try the next backend.
    /// </summary>
    [JsonPropertyName("quality_thresholds")]
    public OcrQualityThresholds QualityThresholds { get; set; } = default!;

}
