// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b40c6d6405568a283b1336728bedea8c7f359fc70e7ad937fa32ada73d60e569
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A catch-all for uncommon errors that do not fit another variant.
/// </summary>
public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
