// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d5ee733859f4cd057d7eb23f8a1ac73619fbaec58423b021a3af075c072ff6c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Byte offset boundary for a page.
///
/// Tracks where a specific page's content starts and ends in the main content string,
/// enabling mapping from byte positions to page numbers. Offsets are guaranteed to be
/// at valid UTF-8 character boundaries when using standard String methods (push_str, push, etc.).
/// </summary>
public sealed class PageBoundary
{
    /// <summary>
    /// Byte offset where this page starts in the content string (UTF-8 valid boundary, inclusive)
    /// </summary>
    [JsonPropertyName("byte_start")]
    public ulong ByteStart { get; set; } = 0;

    /// <summary>
    /// Byte offset where this page ends in the content string (UTF-8 valid boundary, exclusive)
    /// </summary>
    [JsonPropertyName("byte_end")]
    public ulong ByteEnd { get; set; } = 0;

    /// <summary>
    /// Page number (1-indexed)
    /// </summary>
    [JsonPropertyName("page_number")]
    public ulong PageNumber { get; set; } = 0;


    /// <summary>
    /// Parse a <see cref="PageBoundary"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static PageBoundary FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PageBoundary>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse PageBoundary from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse PageBoundary from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
