// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d3f596a22af3ba3dcc92ef3785b2c1b0c821395671aca15cd31f0e5a54201254
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page extraction and tracking configuration.
///
/// Controls how pages are extracted, tracked, and represented in the extraction results.
/// When `None`, page tracking is disabled.
///
/// Page range tracking in chunk metadata (first_page/last_page) is automatically enabled
/// when page boundaries are available and chunking is configured.
/// </summary>
public sealed class PageConfig
{
    /// <summary>
    /// Extract pages as separate array (ExtractionResult.pages)
    /// </summary>
    [JsonPropertyName("extract_pages")]
    public bool ExtractPages { get; set; } = false;

    /// <summary>
    /// Insert page markers in main content string
    /// </summary>
    [JsonPropertyName("insert_page_markers")]
    public bool InsertPageMarkers { get; set; } = false;

    /// <summary>
    /// Page marker format (use {page_num} placeholder)
    /// Default: "\n\n<!-- PAGE {page_num} -->\n\n"
    /// </summary>
    [JsonPropertyName("marker_format")]
    public string MarkerFormat { get; set; } = "\n\n<!-- PAGE {page_num} -->\n\n";


    /// <summary>
    /// Parse a <see cref="PageConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static PageConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PageConfig>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse PageConfig from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse PageConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
