// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page hierarchy structure containing heading levels and block information.
///
/// Used when PDF text hierarchy extraction is enabled. Contains hierarchical
/// blocks with heading levels (H1-H6) for semantic document structure.
/// </summary>
public sealed class PageHierarchy
{
    /// <summary>
    /// Number of hierarchy blocks on this page
    /// </summary>
    [JsonPropertyName("block_count")]
    public ulong BlockCount { get; set; } = 0;

    /// <summary>
    /// Hierarchical blocks with heading levels
    /// </summary>
    [JsonPropertyName("blocks")]
    public List<HierarchicalBlock> Blocks { get; set; } = [];

}
