// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:725873865d33ea26c29b6d4ad73762b9ba39ed2b18ef92c008b9f4e2394a4876
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
