// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:eeef068669f2e06e09b8e1c1d91d7b62e6395f68359e8432ba26b6b35745f96e
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
