// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:16d36e21e58dc8fa83aa26cd90bb5b090a15a5187935f0ff14be673cd7e53514
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
