// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1f85dfe59d1ef0948fd26bf0b7234743d0683a55b171c1e1abce4610efad522f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Convenience type alias for a pooled String.
/// </summary>
public sealed class StringBufferPool : IDisposable
{
    internal IntPtr Handle { get; }

    internal StringBufferPool(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
