// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1fc45c49a7103760fd1682815ff4f5271bbd525c251cd6ce9e3b7b85092e9ec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Structured table grid with cell-level metadata.
///
/// Stores row/column dimensions and a flat list of cells with position info.
/// </summary>
public sealed class TableGrid
{
    /// <summary>
    /// Number of rows in the table.
    /// </summary>
    [JsonPropertyName("rows")]
    public uint Rows { get; set; } = 0;

    /// <summary>
    /// Number of columns in the table.
    /// </summary>
    [JsonPropertyName("cols")]
    public uint Cols { get; set; } = 0;

    /// <summary>
    /// All cells in row-major order.
    /// </summary>
    [JsonPropertyName("cells")]
    public List<GridCell> Cells { get; set; } = [];

}
