// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:da7416dceef3a43b2d95e37dafaf9fc5fa69c76df4f4c20374fcea02a5ec5f03
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
