// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f99c8d02d360528e632c075c65bbad881adec3f4d5b8ff739a79fd196a5ed87a
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class TracingLayerSafeHandle : SafeHandle
{
    internal TracingLayerSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.TracingLayerFree(handle);
        return true;
    }
}
/// <summary>/// A [`tower::Layer`] that wraps each extraction in a semantic tracing span./// </summary>
public sealed class TracingLayer : IDisposable
{
    private readonly TracingLayerSafeHandle _safeHandle;

    internal TracingLayer(IntPtr handle)
    {
        _safeHandle = new TracingLayerSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
