// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : KreuzbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
