// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a21487ee16a8ac19abc71fd0da8956ae1ef5539c7bbd5132eebdf71412a00229
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : KreuzbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
