// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : KreuzbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
