// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ff157d71590cc4b98ee67158c02e6fb5dc2eb880cc75ddcf144586946f6da54c
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
