// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59f64b1b06f35e02379ceae3247870eb2b52518cc03e24544ab56829054f1469
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Semantic classification of an extracted URI./// </summary>
public enum UriKind
{/// <summary>    /// A clickable hyperlink (web URL, file link).    /// </summary>
[JsonPropertyName("hyperlink")]
    Hyperlink,/// <summary>    /// An image or media resource reference.    /// </summary>
[JsonPropertyName("image")]
    Image,/// <summary>    /// An internal anchor or cross-reference target.    /// </summary>
[JsonPropertyName("anchor")]
    Anchor,/// <summary>    /// A citation or bibliographic reference (DOI, academic ref).    /// </summary>
[JsonPropertyName("citation")]
    Citation,/// <summary>    /// A general reference (e.g. `\ref{}` in LaTeX, `:ref:` in RST).    /// </summary>
[JsonPropertyName("reference")]
    Reference,/// <summary>    /// An email address (`mailto:` link or bare email).    /// </summary>
[JsonPropertyName("email")]
    Email,}
