// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e70ae7cc5aa56c59af0669dacbc161ea37f4541b35b975491b50ea37c6800c6c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Year range for bibliographic metadata.
/// </summary>
public sealed class YearRange
{
    [JsonPropertyName("min")]
    public uint? Min { get; set; } = null;

    [JsonPropertyName("max")]
    public uint? Max { get; set; } = null;

    [JsonPropertyName("years")]
    public List<uint> Years { get; set; } = [];

}
