// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:97a1d52486ea9db3472c4fc4bf070a93783db8585b7a03be1de99922a47c344c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    setupFiles: ["./setup.ts"],
  },
});
