/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:b40c6d6405568a283b1336728bedea8c7f359fc70e7ad937fa32ada73d60e569
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface DocumentExtractorBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  extractBytes?(content: string, mimeType: string, config: string): string;
  extractFile?(path: string, mimeType: string, config: string): string;
  supportedMimeTypes(): string;
  priority(): string;
  canHandle(path: string, mimeType: string): string;
}

export class DocumentExtractorAdapter {
  constructor(private bridge: DocumentExtractorBridge) {}

  async extractBytes(content: string, mimeType: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.extractBytes(content, mimeType, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async extractFile(path: string, mimeType: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.extractFile(path, mimeType, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async supportedMimeTypes(): Promise<string> {
    try {
      const result = await this.bridge.supportedMimeTypes();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async priority(): Promise<string> {
    try {
      const result = await this.bridge.priority();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async canHandle(path: string, mimeType: string): Promise<string> {
    try {
      const result = await this.bridge.canHandle(path, mimeType);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
