/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:761e5ccb329b09a02b4f208ce59bbe97c82d8d56c931243fb99693c40ec40a26
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface PostProcessorBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  process?(result: string, config: string): string;
  processingStage(): string;
  shouldProcess(result: string, config: string): string;
  estimatedDurationMs(result: string): string;
  priority(): string;
}

export class PostProcessorAdapter {
  constructor(private bridge: PostProcessorBridge) {}

  async process(result: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.process(result, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async processingStage(): Promise<string> {
    try {
      const result = await this.bridge.processingStage();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async shouldProcess(result: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.shouldProcess(result, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async estimatedDurationMs(result: string): Promise<string> {
    try {
      const result = await this.bridge.estimatedDurationMs(result);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async priority(): Promise<string> {
    try {
      const result = await this.bridge.priority();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
