# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: pdf

test_that("render_pdf_page_first: render_pdf_page_to_png: first page", {
  result <- render_pdf_page_to_png(pdf_bytes = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size), page_index = 0, NULL, NULL)
  expect_true(TRUE)
  expect_true(length(result) >= 100)
})

test_that("render_pdf_page_out_of_range: render_pdf_page_to_png: page out of range", {
  expect_error(render_pdf_page_to_png(pdf_bytes = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size), page_index = 999, NULL, NULL))
})
