# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f713f4416362b4f6f3ee08d6db609b56f1d0dc50d623e64e62c3e8d6cb5ad98
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: pdf

test_that("render_pdf_page_first: render_pdf_page_to_png: first page", {
  result <- render_pdf_page_to_png(pdf_bytes = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size), page_index = 0, NULL, NULL)
  expect_true(TRUE)
  expect_true(length(result) >= 100)
})

test_that("render_pdf_page_out_of_range: render_pdf_page_to_png: page out of range", {
  expect_error(render_pdf_page_to_png(pdf_bytes = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size), page_index = 999, NULL, NULL))
})
