# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a47e9403195e17eb96c9fb33571662840df1e41fa5876c49414e2103ea80a7af
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management

test_that("embedding_backends_clear: Clear all embedding backends and verify list is empty", {
  invisible(clear_embedding_backends())
  expect_true(TRUE)
})

test_that("embedding_backends_list: List all registered embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})
