# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:967e144c67407b9bc8ea7490bcab22792aa24ef81e86941f8ba94eee1551107b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry_operations

test_that("extensions_docx: Get file extensions for DOCX MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  expect_true(TRUE)
})

test_that("extensions_html: Get file extensions for HTML MIME type", {
  result <- get_extensions_for_mime(mime_type = "text/html")
  expect_true(TRUE)
})

test_that("extensions_pdf: Get file extensions for PDF MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/pdf")
  expect_true(TRUE)
})
