# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_extra

test_that("embed_texts_batch: Batch embed texts", {
  result <- embed_texts_async(texts = c("Hello", "World"), config = EmbeddingConfig$from_json(jsonlite::toJSON(list("model" = list("name" = "balanced", "type" = "preset")), auto_unbox = TRUE)))
  expect_true(TRUE)
})
