# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: document_extractor_management

test_that("document_extractors_clear: Clear all document extractors and verify list is empty", {
  invisible(clear_document_extractors())
  expect_true(TRUE)
})

test_that("extractors_list: List all registered document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})
