# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9c896302ba1037f0d7f6e9bf6c742f1bfa5fa60feccba1c2515ef301769ae3ce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations

test_that("extensions_docx: Get file extensions for DOCX MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  expect_true(TRUE)
})

test_that("extensions_html: Get file extensions for HTML MIME type", {
  result <- get_extensions_for_mime(mime_type = "text/html")
  expect_true(TRUE)
})

test_that("extensions_pdf: Get file extensions for PDF MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/pdf")
  expect_true(TRUE)
  expect_true(grepl("pdf", result, fixed = TRUE))
})
