// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The meta-schema itself failed to compile.
/// </summary>
public class BadMetaSchemaException : LoadErrorException
{
    public BadMetaSchemaException(string message) : base(message) { }

    public BadMetaSchemaException(string message, Exception innerException) : base(message, innerException) { }
}
