// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : XbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
