// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
