// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception
{
    public int Code { get; }

    public XbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public XbergException(string message) : base(message)
    {
        Code = 0;
    }

    public XbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
