// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: document_extractor_management

test "document_extractors_clear" {
    // Clear all document extractors and verify list is empty
    suppress_abort();
    _ = try kreuzberg.clear_document_extractors();
}

test "extractors_list" {
    // List all registered document extractors
    suppress_abort();
    _ = try kreuzberg.list_document_extractors();
}
