// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1fe96d2e28a96273ccce01e66f7676434931d4232336c947ea9037b7459c5b94
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: format_specific

test "format_docx_standalone" {
    // Standalone DOCX extraction using extract_bytes_sync
    const result = kreuzberg.extract_bytes_sync("docx/fake.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    try testing.expect(result.content.len >= 20);
}

test "format_pdf_text" {
    // Standalone PDF text extraction using extract_bytes_sync
    const result = kreuzberg.extract_bytes_sync("pdf/fake_memo.pdf", "application/pdf");
    try testing.expect(result.content.len >= 50);
    try testing.expect(std.mem.indexOf(u8, result.content, "Mallori") != null);
    try testing.expect(std.mem.indexOf(u8, result.content, "May") != null);
}

test "format_pptx" {
    // PPTX presentation extraction using extract_file_sync
    const result = kreuzberg.extract_file_sync("pptx/simple.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
}

test "format_xlsx" {
    // XLSX spreadsheet extraction using extract_file_sync
    const result = kreuzberg.extract_file_sync("xlsx/stanley_cups.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
}
