// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: reranker_backend_management

test "clear_reranker_backends" {
    // Clear all reranker backends and verify list is empty
    suppress_abort();
    _ = try kreuzberg.clear_reranker_backends();
}

test "list_reranker_backends" {
    // List all registered reranker backends
    suppress_abort();
    _ = try kreuzberg.list_reranker_backends();
}
