// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4cd6eca0bc15cd7d0fbbf3ab5a796aee9b7384eec49ad14262744e09d5afc369
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile } from 'kreuzberg';

describe('html', () => {
  it('html_complex_layout: Large Wikipedia HTML page to validate complex conversion.', async () => {
    const result = await extractFile("html/taylor_swift.html");
    expect(result.mimeType.trim()).toBe("text/html");
    expect(result.content.length).toBeGreaterThanOrEqual(1000);
  });

  it('html_simple_table: HTML table converted to markdown should retain structure.', async () => {
    const result = await extractFile("html/simple_table.html");
    expect(result.mimeType.trim()).toBe("text/html");
    expect(result.content.length).toBeGreaterThanOrEqual(100);
    expect(result.content).toContain("Product");
    expect(result.content).toContain("Category");
    expect(result.content).toContain("Price");
    expect(result.content).toContain("Stock");
    expect(result.content).toContain("Laptop");
    expect(result.content).toContain("Electronics");
    expect(result.content).toContain("Sample Data Table");
  });
});
