// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, type ExtractionConfig } from 'kreuzberg';

describe('image', () => {
  it('image_metadata_only: JPEG image to validate metadata extraction without OCR.', async () => {
    const result = await extractFile("images/example.jpg", { disable_ocr: true, ocr: null } as ExtractionConfig);
    expect(result.mimeType.trim()).toBe("image/jpeg");
    expect(result.content.length).toBeLessThanOrEqual(200);
  });

  it('image_svg_basic: SVG image extraction.', async () => {
    const result = await extractFile("xml/simple_svg.svg");
    expect(result.mimeType.trim()).toBe("image/svg+xml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });
});
