// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, extract_file_sync, type ExtractionConfig } from 'kreuzberg';

describe('language', () => {
  it('lang_detect_config: Language detection with specific language config', () => {
    extract_file_sync("semantic/mixed_topics.txt", { language_detection: { enabled: true, languages: ["en", "de", "fr"] } } as ExtractionConfig);
  });

  it('lang_detect_english: Language detection works on English text', () => {
    extract_file_sync("semantic/mixed_topics.txt", { language_detection: { enabled: true } } as ExtractionConfig);
  });
});
