// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, extract_file_sync } from 'kreuzberg';

describe('parsing', () => {
  it('parse_json: Parse JSON document format', () => {
    const result = extract_file_sync("json/simple.json");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });

  it('parse_toml: Parse TOML document format', () => {
    const result = extract_file_sync("data_formats/cargo.toml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });

  it('parse_xml: Parse XML document format', () => {
    const result = extract_file_sync("xml/simple_note.xml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });

  it('parse_yaml: Parse YAML document format', () => {
    const result = extract_file_sync("test_fixtures/config.yaml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });
});
