// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:19303aa43814066a719970b6b7e3ab0e8c968b56cf5d3241664eddb9ad126c72
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith

/** E2e tests for category: registry_operations. */
class RegistryOperationsTest {
    @Test
    fun testExtensionsDocx() {
        // Get file extensions for DOCX MIME type
        val result = Kreuzberg.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    @Test
    fun testExtensionsHtml() {
        // Get file extensions for HTML MIME type
        val result = Kreuzberg.getExtensionsForMime("text/html")
    }

    @Test
    fun testExtensionsPdf() {
        // Get file extensions for PDF MIME type
        val result = Kreuzberg.getExtensionsForMime("application/pdf")
        assertTrue(result.contains("pdf"), "expected to contain: " + "pdf")
    }

}
