// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ad5040d65b7881785679b6313f51ed79f4ba11e5595389c3fc52933c24a7c72
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.EmbeddingConfig;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;

/** E2e tests for category: embeddings. */
class EmbeddingsTest {

    @Test
    void testEmbedTextsDifferentPreset() throws Exception {
        // embed_texts: multilingual preset
        var config = EmbeddingConfig.fromJson("{\"model\":\"multilingual\"}");

        var result = Kreuzberg.embedTexts(java.util.List.of("Hello world", "Test"), config);
assertTrue(result.size() >= 2, "expected at least 2 elements");
    }


    @Test
    void testGetEmbeddingPresetKnown() throws Exception {
        // get_embedding_preset: known preset
        var result = Kreuzberg.getEmbeddingPreset("default");

    }


    @Test
    void testGetEmbeddingPresetNominal() throws Exception {
        // get_embedding_preset: nominal case
        var result = Kreuzberg.getEmbeddingPreset("default");

    }


    @Test
    void testGetEmbeddingPresetUnknown() throws Exception {
        // get_embedding_preset: unknown preset fails
        var result = Kreuzberg.getEmbeddingPreset("nonexistent-xyz");
assertTrue(result.isEmpty(), "expected empty value");
    }


    @Test
    void testListEmbeddingPresetsSanity() throws Exception {
        // list_embedding_presets: returns at least one
        var result = Kreuzberg.listEmbeddingPresets();
assertFalse(result.isEmpty(), "expected non-empty value");
    }

}
