// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: html. */
class HtmlTest {
    @Test
    void testHtmlComplexLayout() throws Exception {
        // Large Wikipedia HTML page to validate complex conversion.
        var result = Kreuzberg.extractFile("html/taylor_swift.html");
        assertEquals("text/html", result.mimeType().trim());
        assertTrue(result.content().length() >= 1000, "expected length >= 1000");
    }

    @Test
    void testHtmlSimpleTable() throws Exception {
        // HTML table converted to markdown should retain structure.
        var result = Kreuzberg.extractFile("html/simple_table.html");
        assertEquals("text/html", result.mimeType().trim());
        assertTrue(result.content().length() >= 100, "expected length >= 100");
        assertTrue(result.content().contains("Product"), "expected to contain: " + "Product");
        assertTrue(result.content().contains("Category"), "expected to contain: " + "Category");
        assertTrue(result.content().contains("Price"), "expected to contain: " + "Price");
        assertTrue(result.content().contains("Stock"), "expected to contain: " + "Stock");
        assertTrue(result.content().contains("Laptop"), "expected to contain: " + "Laptop");
        assertTrue(result.content().contains("Electronics"), "expected to contain: " + "Electronics");
        assertTrue(result.content().contains("Sample Data Table"), "expected to contain: " + "Sample Data Table");
    }

}
