// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f713f4416362b4f6f3ee08d6db609b56f1d0dc50d623e64e62c3e8d6cb5ad98
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: ocr_backend_management. */
class OcrBackendManagementTest {

    @Test
    void testOcrBackendsClear() throws Exception {
        // Clear all OCR backends and verify list is empty
        Kreuzberg.clearOcrBackends();


    }


    @Test
    void testOcrBackendsList() throws Exception {
        // List all registered OCR backends
        var result = Kreuzberg.listOcrBackends();


    }


    @Test
    void testOcrBackendsUnregister() throws Exception {
        // Unregister nonexistent OCR backend gracefully
        Kreuzberg.unregisterOcrBackend("nonexistent-backend-xyz");


    }

}
