// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: registry. */
public class RegistryTest {

    @Test
    void testListDocumentExtractors() throws Exception {
        // List document extractors
        var result = Kreuzberg.listDocumentExtractors();


    }


    @Test
    void testListEmbeddingBackends() throws Exception {
        // List embedding backends
        var result = Kreuzberg.listEmbeddingBackends();


    }


    @Test
    void testListOcrBackends() throws Exception {
        // List OCR backends
        var result = Kreuzberg.listOcrBackends();


    }


    @Test
    void testListPostProcessors() throws Exception {
        // List post-processors
        var result = Kreuzberg.listPostProcessors();


    }


    @Test
    void testListRenderers() throws Exception {
        // List renderers
        var result = Kreuzberg.listRenderers();


    }


    @Test
    void testListValidators() throws Exception {
        // List validators
        var result = Kreuzberg.listValidators();


    }

}
