# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:933a661856cd51dc36373a1a7cc3d5db0eb614d5e48f63c53459d1d0ab739514
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
