# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzberg
  ## The version string for this package.
  VERSION = "5.0.0.pre.rc.19"
end
