# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b40c6d6405568a283b1336728bedea8c7f359fc70e7ad937fa32ada73d60e569
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzberg
  ## The version string for this package.
  VERSION = "5.0.0.pre.rc.28"
end
