// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A single label + confidence pair.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClassificationLabel.Builder.class)
@SuppressWarnings("PMD")
public record ClassificationLabel(
    @JsonProperty("label") String label,
    @Nullable @JsonProperty("confidence") Float confidence
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String label = "";
private Float confidence = null;

        /** Sets the label field. */
        @JsonProperty("label")
        public Builder withLabel(final String value) {
            this.label = value;
            return this;
        }

        /** Sets the confidence field. */
        @JsonProperty("confidence")
        public Builder withConfidence(final @Nullable float value) {
            this.confidence = value;
            return this;
        }

        /** Builds the ClassificationLabel instance. */
        public ClassificationLabel build() {
            return new ClassificationLabel(
                label,
                confidence
            );
        }
    }
    // CPD-ON
}
