// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * dBASE field information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DbfFieldInfo.Builder.class)
@SuppressWarnings("PMD")
public record DbfFieldInfo(
    @JsonProperty("name") String name,
    @JsonProperty("field_type") String fieldType
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String name = "";
        @JsonProperty("field_type")
private String fieldType = "";

        /** Sets the name field. */
        @JsonProperty("name")
        public Builder withName(final String value) {
            this.name = value;
            return this;
        }

        /** Sets the fieldType field. */
        @JsonProperty("field_type")
        public Builder withFieldType(final String value) {
            this.fieldType = value;
            return this;
        }

        /** Builds the DbfFieldInfo instance. */
        public DbfFieldInfo build() {
            return new DbfFieldInfo(
                name,
                fieldType
            );
        }
    }
    // CPD-ON
}
