// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bfef3263b3408cbd20a633f7d1c746f6ea861f64f02743645328d5f57f964db6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for email extraction.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailConfig.Builder.class)
public record EmailConfig(@Nullable @JsonProperty("msg_fallback_codepage") Integer msgFallbackCodepage) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("msg_fallback_codepage")
private Integer msgFallbackCodepage = null;

        /** Sets the msgFallbackCodepage field. */
        @JsonProperty("msg_fallback_codepage")
        public Builder withMsgFallbackCodepage(final @Nullable int value) {
            this.msgFallbackCodepage = value;
            return this;
        }

        /** Builds the EmailConfig instance. */
        public EmailConfig build() {
            return new EmailConfig(
                msgFallbackCodepage
            );
        }
    }
    // CPD-ON
}
