// DO NOT EDIT - auto-generated by alef
// alef:hash:9f713f4416362b4f6f3ee08d6db609b56f1d0dc50d623e64e62c3e8d6cb5ad98
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
