// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the extracted text was produced.
 */
public enum ExtractionMethod {
    Native("native"),
    Ocr("ocr"),
    Mixed("mixed");

    /** The string value. */
    private final String value;

    ExtractionMethod(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExtractionMethod fromValue(final String value) {
        for (ExtractionMethod e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
