// DO NOT EDIT - auto-generated by alef
// alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
package dev.kreuzberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) {
    super(message);
  }

  /** Creates a new HeuristicsErrorException with the given message and cause. */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
