// DO NOT EDIT - auto-generated by alef
// alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
package dev.kreuzberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) {
    super(message);
  }

  /** Creates a new HeuristicsErrorException with the given message and cause. */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
