// DO NOT EDIT - auto-generated by alef
// alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
package dev.kreuzberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdMismatchException with the given message. */
  public IdMismatchException(final String message) {
    super(message);
  }

  /** Creates a new IdMismatchException with the given message and cause. */
  public IdMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
