// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends KreuzbergRsException {
    /** Creates a new InvalidInputException. */
    public InvalidInputException(final String message) {
        super(1, message);
    }

    /** Creates a new InvalidInputException with a cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
