// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bfef3263b3408cbd20a633f7d1c746f6ea861f64f02743645328d5f57f964db6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

/** Exception thrown by KreuzbergRs. */
@SuppressWarnings("checkstyle:LineLength")
public class KreuzbergRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new KreuzbergRsException. */
    public KreuzbergRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new KreuzbergRsException with a cause. */
    public KreuzbergRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
