// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:967e144c67407b9bc8ea7490bcab22792aa24ef81e86941f8ba94eee1551107b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/** Exception thrown by KreuzbergRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class KreuzbergRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new KreuzbergRsException. */
    public KreuzbergRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new KreuzbergRsException with a cause. */
    public KreuzbergRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
