// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link type classification.
 */
public enum LinkType {
    /**
     * Anchor link (#section)
     */
    Anchor("anchor"),
    /**
     * Internal link (same domain)
     */
    Internal("internal"),
    /**
     * External link (different domain)
     */
    External("external"),
    /**
     * Email link (mailto:)
     */
    Email("email"),
    /**
     * Phone link (tel:)
     */
    Phone("phone"),
    /**
     * Other link type
     */
    Other("other");

    /** The string value. */
    private final String value;

    LinkType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static LinkType fromValue(final String value) {
        for (LinkType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
