// DO NOT EDIT - auto-generated by alef
// alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
package dev.kreuzberg;

/**
 * An internal `Mutex` or `RwLock` was found in a poisoned state.
 */
public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
