// DO NOT EDIT - auto-generated by alef
// alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
package dev.kreuzberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParsingException with the given message. */
  public ParsingException(final String message) {
    super(message);
  }

  /** Creates a new ParsingException with the given message and cause. */
  public ParsingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
