// DO NOT EDIT - auto-generated by alef
// alef:hash:a47e9403195e17eb96c9fb33571662840df1e41fa5876c49414e2103ea80a7af
package dev.kreuzberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
