// DO NOT EDIT - auto-generated by alef
// alef:hash:a47e9403195e17eb96c9fb33571662840df1e41fa5876c49414e2103ea80a7af
package dev.kreuzberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends KreuzbergErrorException {
    /** Creates a new RerankingException with the given message. */
    public RerankingException(final String message) {
        super(message);
    }

    /** Creates a new RerankingException with the given message and cause. */
    public RerankingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
