// DO NOT EDIT - auto-generated by alef
// alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
