// DO NOT EDIT - auto-generated by alef
// alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
package dev.kreuzberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends KreuzbergErrorException {
    /** Creates a new TranscriptionException with the given message. */
    public TranscriptionException(final String message) {
        super(message);
    }

    /** Creates a new TranscriptionException with the given message and cause. */
    public TranscriptionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
