// DO NOT EDIT - auto-generated by alef
// alef:hash:a21487ee16a8ac19abc71fd0da8956ae1ef5539c7bbd5132eebdf71412a00229
package dev.kreuzberg;

/**
 * The document's MIME type is not supported by any registered extractor.
 */
public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
