// Generated by alef. Do not edit by hand.
// alef:hash:3e9750349b7aeaefee4dc21b4616209b660931a3204927feb49e14ec77cbd152

package io.xberg

/// Bridge adapter for IRenderer implementations.
///
/// Wraps a user-supplied IRenderer instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class RendererAdapter(private val impl: IRenderer) : IRenderer {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()

    override fun renderResult(result: ExtractedDocument): String {
        return impl.renderResult(result)
    }


}
