// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:683c31bf789a58a6a2e1c4690eabfb3d2005f7b1336342e82be6918b3be6aa38
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Archive (ZIP/TAR/7Z) metadata.
 *
 * Extracted from compressed archive files containing file lists and size information.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ArchiveMetadataBuilder {

    private String format = "";
    @JsonProperty("fileCount")
    private long fileCount = 0;
    @JsonProperty("fileList")
    private List<String> fileList = List.of();
    @JsonProperty("totalSize")
    private long totalSize = 0;
    @JsonProperty("compressedSize")
    private Optional<Long> compressedSize = Optional.empty();

    /** Sets the format field. */
    public ArchiveMetadataBuilder withFormat(final String value) {
        this.format = value;
        return this;
    }

    /** Sets the fileCount field. */
    public ArchiveMetadataBuilder withFileCount(final long value) {
        this.fileCount = value;
        return this;
    }

    /** Sets the fileList field. */
    public ArchiveMetadataBuilder withFileList(final List<String> value) {
        this.fileList = value;
        return this;
    }

    /** Sets the totalSize field. */
    public ArchiveMetadataBuilder withTotalSize(final long value) {
        this.totalSize = value;
        return this;
    }

    /** Sets the compressedSize field. */
    public ArchiveMetadataBuilder withCompressedSize(final Optional<Long> value) {
        this.compressedSize = value;
        return this;
    }

    /** Builds the ArchiveMetadata instance. */
    public ArchiveMetadata build() {
        return new ArchiveMetadata(
            format,
            fileCount,
            fileList,
            totalSize,
            compressedSize.orElse(null)
        );
    }
}
