// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1c5e27682799cab0962599656af7ad768bc57a54bf6d7db6f9875be7c94959df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BBox(float x1, float y1, float x2, float y2) {
}
