// DO NOT EDIT - auto-generated by alef
// alef:hash:0d87f8f8dc324502080bd8e1d74c9419b43b24eaddf24f5da40aeed63c5311a8
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
