// DO NOT EDIT - auto-generated by alef
// alef:hash:2439ef12b53ebffd5905ee8ec3f3b1444c786e26cfd25a6d4d49a9886adc6609
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
