// DO NOT EDIT - auto-generated by alef
// alef:hash:76c2ec1f324cb8ee2a738c9bf0d81c5255a33b24a0b00d5bf70ab92393ea3beb
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
