// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0bf455ee86464e8ade6eefe592b35d9e818fd08d15638383ab430b83264a6c82
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Citation file metadata (RIS, PubMed, EndNote).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CitationMetadataBuilder.class)
public record CitationMetadata(
    @JsonProperty("citation_count") long citationCount,
    @Nullable String format,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> authors,
    @Nullable @JsonProperty("year_range") YearRange yearRange,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> dois,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> keywords
) {
    public static CitationMetadataBuilder builder() {
        return new CitationMetadataBuilder();
    }
}
