// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e5f27068659ba43b491e6f8e9d4e4b65ac869b7c11df89c2008ff3a871bfc945
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Common metadata fields extracted from a PDF.
 */
public record CommonPdfMetadata(Optional<String> title, Optional<String> subject, Optional<List<String>> authors,
		Optional<List<String>> keywords, @JsonProperty("created_at") Optional<String> createdAt,
		@JsonProperty("modified_at") Optional<String> modifiedAt,
		@JsonProperty("created_by") Optional<String> createdBy) {
}
