// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:795f354ca149f0f6166128bb4821ee53e236106d3ec78b21b809bfc2b76eca08
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Page-level detection result containing all detections and page metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectionResult(@JsonProperty("page_width") int pageWidth, @JsonProperty("page_height") int pageHeight,
		@JsonInclude(JsonInclude.Include.NON_NULL) List<LayoutDetection> detections) {
}
