// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fae55c57c458ce737d4e5c94de77f5a4a84060a5065c878891c00cb1ac71bd6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Request parameters for MIME type detection.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectMimeTypeParams(String path, @JsonProperty("use_content") boolean useContent) {
}
