// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1cbf979436c5ca2b0546c0e073db1317a90903bca2755c17eb72f1b055ed26a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OpenWebUI "Docling" engine response format.
 *
 * Returned by {@code POST /v1/convert/file} for docling-serve compatibility.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DoclingCompatResponse(String document, String status) {
}
