// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f16e1b98c2ba25158607df081f3986cc5812e9995256ac706d16c6e04e156605
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/**
 * Configuration for email extraction.
 */
public class EmailConfigBuilder {

	private Optional<Integer> msgFallbackCodepage = Optional.empty();

	/** Sets the msgFallbackCodepage field. */
	public EmailConfigBuilder withMsgFallbackCodepage(final Optional<Integer> value) {
		this.msgFallbackCodepage = value;
		return this;
	}

	/** Builds the EmailConfig instance. */
	public EmailConfig build() {
		return new EmailConfig(msgFallbackCodepage);
	}
}
