// DO NOT EDIT - auto-generated by alef
// alef:hash:d8a65c71bf16ca5ecc77ac29a0b26feed08ce8aa37a4b7b292100a52474bf2e6
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
