// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:55a88e4c4b0f1dd0a2ef749c940ff10934728e95bd192d208e42b54fd5a22453
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Error metadata (for batch operations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ErrorMetadata(@JsonProperty("error_type") String errorType, String message) {
}
