// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request parameters for bytes extraction.
 */
public record ExtractBytesParams(
    /** Base64-encoded file content */
    String data,
    /** Optional MIME type hint (auto-detected if not provided) */
    @JsonProperty("mime_type") Optional<String> mimeType,
    /** Extraction configuration (JSON object) */
    Optional<Object> config,
    /** Password for encrypted PDFs */
    @JsonProperty("pdf_password") Optional<String> pdfPassword,
    /** Wire format for the response: "json" (default) or "toon" */
    @JsonProperty("response_format") Optional<String> responseFormat
) {
}
