// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e1942d73be1be003844dd5d073114e1d9d6401ed278d57639c9333c9e39e8b98
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * General extraction result used by the core extraction API.
 *
 * This is the main result type returned by all extraction functions.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExtractionResultBuilder.class)
public record ExtractionResult(
    String content,
    @JsonProperty("mimeType") String mimeType,
    Metadata metadata,
    @Nullable @JsonProperty("extractionMethod") ExtractionMethod extractionMethod,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<Table> tables,
    @Nullable @JsonProperty("detectedLanguages") List<String> detectedLanguages,
    @Nullable List<Chunk> chunks,
    @Nullable List<ExtractedImage> images,
    @Nullable List<PageContent> pages,
    @Nullable List<Element> elements,
    @Nullable @JsonProperty("djotContent") DjotContent djotContent,
    @Nullable @JsonProperty("ocrElements") List<OcrElement> ocrElements,
    @Nullable DocumentStructure document,
    @Nullable @JsonProperty("extractedKeywords") List<Keyword> extractedKeywords,
    @Nullable @JsonProperty("qualityScore") Double qualityScore,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("processingWarnings") List<ProcessingWarning> processingWarnings,
    @Nullable List<PdfAnnotation> annotations,
    @Nullable List<ArchiveEntry> children,
    @Nullable List<Uri> uris,
    @Nullable @JsonProperty("structuredOutput") Object structuredOutput,
    @Nullable @JsonProperty("codeIntelligence") String codeIntelligence,
    @Nullable @JsonProperty("llmUsage") List<LlmUsage> llmUsage,
    @Nullable @JsonProperty("formattedContent") String formattedContent,
    @Nullable @JsonProperty("ocrInternalDocument") String ocrInternalDocument
) {
    public static ExtractionResultBuilder builder() {
        return new ExtractionResultBuilder();
    }

    /**
     * Parse a {@code ExtractionResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ExtractionResult fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ExtractionResult.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ExtractionResult from JSON: " + e.getMessage(), e);
        }
    }
}
