// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f9f0d7d830dbb64faba300fee54e028af0e099cc5a93cd6824889011f072a5c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the extracted text was produced.
 */
public enum ExtractionMethod {
    Native("native"), Ocr("ocr"), Mixed("mixed");

    /** The string value. */
    private final String value;

    ExtractionMethod(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExtractionMethod fromValue(final String value) {
        for (ExtractionMethod e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
