// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5692b1236c8c918db1089c516e223f2ded074840b4a9076cbb69be8df3b06b69
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the extracted text was produced.
 */
public enum ExtractionMethod {
	Native("native"), Ocr("ocr"), Mixed("mixed");

	/** The string value. */
	private final String value;

	ExtractionMethod(final String value) {
		this.value = value;
	}

	/** Returns the string value. */
	@JsonValue
	public String getValue() {
		return value;
	}

	/** Creates an instance from a string value. */
	@JsonCreator
	public static ExtractionMethod fromValue(final String value) {
		for (ExtractionMethod e : values()) {
			if (e.value.equalsIgnoreCase(value)) {
				return e;
			}
		}
		throw new IllegalArgumentException("Unknown value: " + value);
	}
}
