// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2ea56170fae300cf46a13a5d4c6fe4816fa5cfc8a6100f56489d1e98a550bc03
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FictionBook (FB2) metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class FictionBookMetadataBuilder {

    @JsonProperty("genres")
    private List<String> genres = List.of();
    @JsonProperty("sequences")
    private List<String> sequences = List.of();
    @JsonProperty("annotation")
    private Optional<String> annotation = Optional.empty();

    /** Sets the genres field. */
    @JsonProperty("genres")
    public FictionBookMetadataBuilder withGenres(final List<String> value) {
        this.genres = value;
        return this;
    }

    /** Sets the sequences field. */
    @JsonProperty("sequences")
    public FictionBookMetadataBuilder withSequences(final List<String> value) {
        this.sequences = value;
        return this;
    }

    /** Sets the annotation field. */
    @JsonProperty("annotation")
    public FictionBookMetadataBuilder withAnnotation(final Optional<String> value) {
        this.annotation = value;
        return this;
    }

    /** Builds the FictionBookMetadata instance. */
    public FictionBookMetadata build() {
        return new FictionBookMetadata(genres, sequences, annotation.orElse(null));
    }
}
