// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dce5f644f9092c1d22a87cce6b536eed3b3e8deafe229f1b3df49eef61842fc9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * FictionBook (FB2) metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class FictionBookMetadataBuilder {

    private List<String> genres = List.of();
    private List<String> sequences = List.of();
    private Optional<String> annotation = Optional.empty();

    /** Sets the genres field. */
    public FictionBookMetadataBuilder withGenres(final List<String> value) {
        this.genres = value;
        return this;
    }

    /** Sets the sequences field. */
    public FictionBookMetadataBuilder withSequences(final List<String> value) {
        this.sequences = value;
        return this;
    }

    /** Sets the annotation field. */
    public FictionBookMetadataBuilder withAnnotation(final Optional<String> value) {
        this.annotation = value;
        return this;
    }

    /** Builds the FictionBookMetadata instance. */
    public FictionBookMetadata build() {
        return new FictionBookMetadata(
            genres,
            sequences,
            annotation.orElse(null)
        );
    }
}
