// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6bc826afa8e3277d21f6e096de56d0b04c50dfb5479dbf651b1e95c99071f384
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/**
 * Hierarchy extraction configuration for PDF text structure analysis.
 *
 * Enables extraction of document hierarchy levels (H1-H6) based on font size
 * clustering and semantic analysis. When enabled, hierarchical blocks are
 * included in page content.
 */
public class HierarchyConfigBuilder {

	private boolean enabled = false;
	private long kClusters = 0;
	private boolean includeBbox = false;
	private Optional<Float> ocrCoverageThreshold = Optional.empty();

	/** Sets the enabled field. */
	public HierarchyConfigBuilder withEnabled(final boolean value) {
		this.enabled = value;
		return this;
	}

	/** Sets the kClusters field. */
	public HierarchyConfigBuilder withKClusters(final long value) {
		this.kClusters = value;
		return this;
	}

	/** Sets the includeBbox field. */
	public HierarchyConfigBuilder withIncludeBbox(final boolean value) {
		this.includeBbox = value;
		return this;
	}

	/** Sets the ocrCoverageThreshold field. */
	public HierarchyConfigBuilder withOcrCoverageThreshold(final Optional<Float> value) {
		this.ocrCoverageThreshold = value;
		return this;
	}

	/** Builds the HierarchyConfig instance. */
	public HierarchyConfig build() {
		return new HierarchyConfig(enabled, kClusters, includeBbox, ocrCoverageThreshold);
	}
}
