// DO NOT EDIT - auto-generated by alef
// alef:hash:8e4fdb66092022610657f974aaed89d3254dfb7754aef9b6d6b4c8369f058c98
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
