// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d98de4f6f86c88977a2b63de5899d1a9d19bfc1c0f26016c9146aa66e79a5d7b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Extracted keyword with metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Keyword(
        /** The keyword text. */
        String text,
        /** Relevance score (higher is better, algorithm-specific range). */
        float score,
        /** Algorithm that extracted this keyword. */
        KeywordAlgorithm algorithm,
        /** Optional positions where keyword appears in text (character offsets). */
        @Nullable List<Long> positions) {
}
