// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:932041ad341feac0d0740bde4cd325a4d6b3c316358d59a38b93607f9ae5c92f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single layout detection result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LayoutDetection(
    @JsonProperty("class_name") LayoutClass className,
    float confidence,
    BBox bbox
) {
}
