// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4cec681a406a9ce7ef3190d26a690fe1f708c5c6c3b567e2ee64d9d85e46849a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Link element metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LinkMetadata(
		/** The href URL value */
		String href,
		/** Link text content (normalized) */
		String text,
		/** Optional title attribute */
		Optional<String> title,
		/** Link type classification */
		@JsonProperty("link_type") LinkType linkType,
		/** Rel attribute values */
		@JsonInclude(JsonInclude.Include.NON_NULL) List<String> rel,
		/** Additional attributes as key-value pairs */
		@JsonInclude(JsonInclude.Include.NON_NULL) List<String> attributes) {
}
