// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8f4187a7828898c7118f7ab153446bc8a74b86c5a9b4b319c2f1292b7266e35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Model manifest entry for cache management.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ManifestEntryResponse(
        /** Relative path within the cache directory */
        @JsonProperty("relative_path") String relativePath,
        /** SHA256 checksum of the model file */
        String sha256,
        /** Expected file size in bytes */
        @JsonProperty("size_bytes") long sizeBytes,
        /** HuggingFace source URL for downloading */
        @JsonProperty("source_url") String sourceUrl) {
}
