// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5fa651013518f0273a9d478f29f0080eecd7135f5199ed2a77282360df6e9f2a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Rotation information for an OCR element.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrRotation(
		/** Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR). */
		@JsonProperty("angle_degrees") double angleDegrees,
		/** Confidence score for the rotation detection. */
		Optional<Double> confidence) {
}
