// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:60f86ff6e571754399c81838a0c7326f9ad4d56dde37e9235991c8dc8b74970b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box for an OCR-detected table in pixel coordinates.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrTableBoundingBox(int left, int top, int right, int bottom) {
}
