// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a12cd0a7170f7057bc5f096a1e520e96e41eb51a343e9279b856cbea2df886b8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/**
 * Bounding box for an OCR-detected table in pixel coordinates.
 */
public record OcrTableBoundingBox(int left, int top, int right, int bottom) {
}
