// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2b6f0ac1f80d757165fa6468b4a99164df2add50f1886ec9926e055983ca858
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box for an OCR-detected table in pixel coordinates.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrTableBoundingBox(int left, int top, int right, int bottom) {
}
