// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8f348439382a656c1e123f5d2a0bbc02c90bd5c5a4982639246410159286c96d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Layout detection results for a single page.
 */
public record PageLayoutResult(@JsonProperty("page_index") long pageIndex, List<String> regions,
		@JsonProperty("page_width_pts") float pageWidthPts, @JsonProperty("page_height_pts") float pageHeightPts,
		/** Width of the rendered image used for layout detection (pixels). */
		@JsonProperty("render_width_px") int renderWidthPx,
		/** Height of the rendered image used for layout detection (pixels). */
		@JsonProperty("render_height_px") int renderHeightPx) {
}
