// DO NOT EDIT - auto-generated by alef
// alef:hash:b9704a0f31ce6c7f38bd8e7f29bd5bc473acf96007ef2e58505043e18c26db97
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
