// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A PDF annotation extracted from a document page.
 */
public record PdfAnnotation(
    /** The type of annotation. */
    @JsonProperty("annotation_type") PdfAnnotationType annotationType,
    /** Text content of the annotation (e.g., comment text, link URL). */
    Optional<String> content,
    /** Page number where the annotation appears (1-indexed). */
    @JsonProperty("page_number") long pageNumber,
    /** Bounding box of the annotation on the page. */
    @JsonProperty("bounding_box") Optional<String> boundingBox
) {
}
