// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PowerPoint presentation metadata.
 *
 * Extracted from PPTX files containing slide counts and presentation details.
 */
public record PptxMetadata(
    /** Total number of slides in the presentation */
    @JsonProperty("slide_count") long slideCount,
    /** Names of slides (if available) */
    @JsonProperty("slide_names") List<String> slideNames,
    /** Number of embedded images */
    @JsonProperty("image_count") Optional<Long> imageCount,
    /** Number of tables */
    @JsonProperty("table_count") Optional<Long> tableCount
) {
    public static PptxMetadataBuilder builder() {
        return new PptxMetadataBuilder();
    }
}
