// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:51ca440eca770eb451fe7f46a41dfef10b006c34576cf2932c622408fdd7e77a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Application properties from docProps/app.xml for PPTX
 *
 * Contains PowerPoint-specific document metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PptxAppPropertiesBuilder.class)
public record PptxAppProperties(
    @Nullable String application,
    @Nullable @JsonProperty("appVersion") String appVersion,
    @Nullable @JsonProperty("totalTime") Integer totalTime,
    @Nullable String company,
    @Nullable @JsonProperty("docSecurity") Integer docSecurity,
    @Nullable @JsonProperty("scaleCrop") Boolean scaleCrop,
    @Nullable @JsonProperty("linksUpToDate") Boolean linksUpToDate,
    @Nullable @JsonProperty("sharedDoc") Boolean sharedDoc,
    @Nullable @JsonProperty("hyperlinksChanged") Boolean hyperlinksChanged,
    @Nullable Integer slides,
    @Nullable Integer notes,
    @Nullable @JsonProperty("hiddenSlides") Integer hiddenSlides,
    @Nullable @JsonProperty("multimediaClips") Integer multimediaClips,
    @Nullable @JsonProperty("presentationFormat") String presentationFormat,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("slideTitles") List<String> slideTitles
) {
    public static PptxAppPropertiesBuilder builder() {
        return new PptxAppPropertiesBuilder();
    }

    /**
     * Parse a {@code PptxAppProperties} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static PptxAppProperties fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, PptxAppProperties.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse PptxAppProperties from JSON: " + e.getMessage(), e);
        }
    }
}
