// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4de32ac4a1dc52f6a000864feae2888a3d021640cf90054438f58811cb4e4655
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Outlook PST archive metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class PstMetadataBuilder {

    @JsonProperty("message_count")
    private long messageCount = 0;

    /** Sets the messageCount field. */
    @JsonProperty("message_count")
    public PstMetadataBuilder withMessageCount(final long value) {
        this.messageCount = value;
        return this;
    }

    /** Builds the PstMetadata instance. */
    public PstMetadata build() {
        return new PstMetadata(
            messageCount
        );
    }
}
