// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dc0c452bee5a290ec3d950c50f88a4d2280301935ab152e678690efb609e79bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum ReductionLevel {
    Off("off"),
    Light("light"),
    Moderate("moderate"),
    Aggressive("aggressive"),
    Maximum("maximum");

    /** The string value. */
    private final String value;

    ReductionLevel(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ReductionLevel fromValue(final String value) {
        for (ReductionLevel e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
