// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c405d2e36e0f0834a80e773221bbb068ccf6399561ab11a4fccff9597efcf681
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A supported document format entry.
 *
 * Represents a file extension and its corresponding MIME type that Kreuzberg can process.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SupportedFormat(String extension, @JsonProperty("mime_type") String mimeType) {
}
