// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Token reduction configuration.
 */
public record TokenReductionOptions(
    /** Reduction mode: "off", "light", "moderate", "aggressive", "maximum" */
    String mode,
    /** Preserve important words (capitalized, technical terms) */
    @JsonProperty("preserve_important_words") boolean preserveImportantWords
) {
}
