// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ecb46edc88c6715e5e4e5003afc1b20d99ad49faa5507cec25154b5e6bc7abd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Processing options for tree-sitter code analysis.
 *
 * Controls which analysis features are enabled when extracting code files.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TreeSitterProcessConfig(
		/**
		 * Extract structural items (functions, classes, structs, etc.). Default: true.
		 */
		boolean structure,
		/** Extract import statements. Default: true. */
		boolean imports,
		/** Extract export statements. Default: true. */
		boolean exports,
		/** Extract comments. Default: false. */
		boolean comments,
		/** Extract docstrings. Default: false. */
		boolean docstrings,
		/** Extract symbol definitions. Default: false. */
		boolean symbols,
		/** Include parse diagnostics. Default: false. */
		boolean diagnostics,
		/** Maximum chunk size in bytes. {@code None} disables chunking. */
		@JsonProperty("chunk_max_size") Optional<Long> chunkMaxSize, /** Content rendering mode for code extraction. */
		@JsonProperty("content_mode") CodeContentMode contentMode) {
	public static TreeSitterProcessConfigBuilder builder() {
		return new TreeSitterProcessConfigBuilder();
	}
}
