// DO NOT EDIT - auto-generated by alef
// alef:hash:2a5c6cf1d41b8fe8f71f6aa3d7ced6d093c5208b507a571f8cfe5a8e66938d49
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
