// DO NOT EDIT - auto-generated by alef
// alef:hash:6f8b8a46f5d97c604bad9f4c5ea0b5a14c0ebd523f56150b726fa477d8348d12
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
