// DO NOT EDIT - auto-generated by alef
// alef:hash:d04aeea7f020bffe502a1b8a2cf679a7d38e425c9ae5a19a970c0e9e8937b1d0
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
