// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:82983397aeb73b646361df3b33fcff6d96d8e9820a62aeda39a465284f0887f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * YAKE-specific parameters.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class YakeParamsBuilder {

    private long windowSize = 0;

    /** Sets the windowSize field. */
    public YakeParamsBuilder withWindowSize(final long value) {
        this.windowSize = value;
        return this;
    }

    /** Builds the YakeParams instance. */
    public YakeParams build() {
        return new YakeParams(
            windowSize
        );
    }
}
