// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * YAKE-specific parameters.
 */
public record YakeParams(@JsonProperty("window_size") long windowSize) {
    public static YakeParamsBuilder builder() {
        return new YakeParamsBuilder();
    }
}
