// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cd0aa05ea238e42994b8e4a715eaa08c5a1c7ceb328ee19ae32d5fdc11b2f106
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/**
 * YAKE-specific parameters.
 */
public class YakeParamsBuilder {

	private long windowSize = 0;

	/** Sets the windowSize field. */
	public YakeParamsBuilder withWindowSize(final long value) {
		this.windowSize = value;
		return this;
	}

	/** Builds the YakeParams instance. */
	public YakeParams build() {
		return new YakeParams(windowSize);
	}
}
