# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc """
  Hardware acceleration configuration for ONNX Runtime models.

  Controls which execution provider (CPU, CoreML, CUDA, TensorRT) is used
  for inference in layout detection and embedding generation.

  # Example

  ```rust
  use kreuzberg::AccelerationConfig;

  // Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere
  let config = AccelerationConfig::default();

  // Force CPU only
  let config = AccelerationConfig {
      provider: kreuzberg::ExecutionProviderType::Cpu,
      ..Default::default()
  };
  ```
  """

  @typedoc "Hardware acceleration configuration for ONNX Runtime models."
  @type t :: %__MODULE__{
          provider: String.t() | nil,
          device_id: non_neg_integer()
        }

  defstruct provider: :auto,
            device_id: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
