# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c473636cc72277e666c324ff68b2d824777c47d132473ff32e3c277a53adec62
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AnchorProperties do
  @moduledoc "Properties for anchored drawings."

  defstruct behind_doc: false,
            layout_in_cell: false,
            relative_height: 0,
            position_h: "",
            position_v: "",
            wrap_type: ""
end
