# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:046f21883c5519ff528117c9799f5809bd8a9eaac6ee16a4185d679e90035955
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AnnotationKind do
  @moduledoc "Types of inline text annotations."

  @type t :: term()

  @type bold :: :bold
  @type italic :: :italic
  @type underline :: :underline
  @type strikethrough :: :strikethrough
  @type code :: :code
  @type subscript :: :subscript
  @type superscript :: :superscript
  @type link :: %{type: :link, url: term(), title: term()}
  @type highlight :: :highlight
  @type color :: %{type: :color, value: term()}
  @type font_size :: %{type: :font_size, value: term()}
  @type custom :: %{type: :custom, name: term(), value: term()}
end
