# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c4fc6be92bd3591052b318b061068935a7ac3247385d396ab8162cfbc91422a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
