# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:423e7923485d66a45c541f6aa1131dd0bf4133712f215075cf3a3d9b376fd99a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc """
  A single file extracted from an archive.

  When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
  enabled, each processable file produces its own full `ExtractionResult`.
  """

  @typedoc "A single file extracted from an archive."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          mime_type: String.t() | nil,
          result: map()
        }

  defstruct path: nil,
            mime_type: nil,
            result: nil
end
