# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.AudioMetadata do
  @moduledoc """
  Audio/video file metadata.

  Populated from container tags (ID3v2, MP4 atoms, Vorbis comments, etc.) and
  PCM decode properties. Available when the `transcription-types` feature is enabled.
  """

  @typedoc "Audio/video file metadata."
  @type t :: %__MODULE__{
          duration_ms: non_neg_integer() | nil,
          codec: String.t() | nil,
          container: String.t() | nil,
          sample_rate_hz: non_neg_integer() | nil,
          channels: non_neg_integer() | nil,
          bitrate: non_neg_integer() | nil
        }

  defstruct duration_ms: nil,
            codec: nil,
            container: nil,
            sample_rate_hz: nil,
            channels: nil,
            bitrate: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
