# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:761e5ccb329b09a02b4f208ce59bbe97c82d8d56c931243fb99693c40ec40a26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  @typedoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."
  @type t :: %__MODULE__{
          x1: float(),
          y1: float(),
          x2: float(),
          y2: float()
        }

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
