# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchExtractFilesParams do
  @moduledoc "Request parameters for batch file extraction."

  defstruct paths: [],
            config: nil,
            pdf_password: nil,
            file_configs: nil,
            response_format: nil
end
