# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b32b8f8f19dab7ebfd946f28085e65b789350cb4b860970172934d5b3c3d081
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc "Batch item for byte array extraction."

  defstruct content: "",
            mime_type: "",
            config: nil
end
