# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7443772d3f27c1d69717f0092fa42d48e812a88becd7ed4f8660f925b408e057
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchFileItem do
  @moduledoc "Batch item for file extraction."

  defstruct path: "",
            config: nil
end
