# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BibtexMetadata do
  @moduledoc "BibTeX bibliography metadata."

  @typedoc "BibTeX bibliography metadata."
  @type t :: %__MODULE__{
          entry_count: non_neg_integer(),
          citation_keys: [String.t()],
          authors: [String.t()],
          year_range: map() | nil,
          entry_types: map() | nil
        }

  defstruct entry_count: 0,
            citation_keys: [],
            authors: [],
            year_range: nil,
            entry_types: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
