# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2c197fb1f900709a6313cdd950031201b322109ee885042d1f29515d173d9eb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheWarmParams do
  @moduledoc "Request parameters for cache warm (model download)."

  defstruct all_embeddings: false,
            embedding_model: nil
end
