# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:967e144c67407b9bc8ea7490bcab22792aa24ef81e86941f8ba94eee1551107b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkSizing do
  @moduledoc """
  How chunk size is measured.

  Defaults to `Characters` (Unicode character count). When using token-based sizing,
  chunks are sized by token count according to the specified tokenizer.

  Token-based sizing uses HuggingFace tokenizers loaded at runtime. Any tokenizer
  available on HuggingFace Hub can be used, including OpenAI-compatible tokenizers
  (e.g., `Xenova/gpt-4o`, `Xenova/cl100k_base`).
  """

  @typedoc "How chunk size is measured."
  @type t :: term()

  @typedoc "Size measured in Unicode characters (default)."
  @type characters :: :characters
  @typedoc "Size measured in tokens from a HuggingFace tokenizer."
  @type tokenizer :: %{type: :tokenizer, model: String.t(), cache_dir: String.t()}
end
