# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67069c31e43a039fec68940be1f6fb787e1452c7d88d1b26592beb878c059f08
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  @type t :: %__MODULE__{
    text: String.t() | nil,
    max_characters: non_neg_integer() | nil,
    overlap: non_neg_integer() | nil,
    chunker_type: String.t() | nil,
    topic_threshold: float() | nil
  }

  defstruct text: nil,
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
