# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkingDecision do
  @moduledoc "The chunking decision made by the analyzer."

  @typedoc "The chunking decision made by the analyzer."
  @type t :: term()

  @typedoc "Process without chunking (small file, text layer detected, etc.)"
  @type no_chunking :: %{type: :no_chunking, reason: map()}
  @typedoc "Chunk according to plan."
  @type chunk :: %{type: :chunk, plan: Kreuzberg.ChunkPlan.t()}
  @typedoc "Use user-provided chunk overrides."
  @type use_overrides :: %{type: :use_overrides, user_chunks: [map()]}
end
