# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkMetadata do
  @moduledoc "Metadata about a chunk's position in the original document."

  @typedoc "Metadata about a chunk's position in the original document."
  @type t :: %__MODULE__{
          byte_start: non_neg_integer(),
          byte_end: non_neg_integer(),
          token_count: non_neg_integer() | nil,
          chunk_index: non_neg_integer(),
          total_chunks: non_neg_integer(),
          first_page: non_neg_integer() | nil,
          last_page: non_neg_integer() | nil,
          heading_context: map() | nil,
          image_indices: [non_neg_integer()]
        }

  defstruct byte_start: 0,
            byte_end: 0,
            token_count: nil,
            chunk_index: 0,
            total_chunks: 0,
            first_page: nil,
            last_page: nil,
            heading_context: nil,
            image_indices: []
end
