# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:50222d259cd2e650c113e244bbbf2dec2dfeade8b9e2eb37e3f482361d2db375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkingConfig do
  @moduledoc "Chunking configuration."

  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil
end
