# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkingDecision do
  @moduledoc "The chunking decision made by the analyzer."

  @typedoc "The chunking decision made by the analyzer."
  @type t :: term()

  @typedoc "Process without chunking (small file, text layer detected, etc.)"
  @type no_chunking :: %{type: :no_chunking, reason: map()}
  @typedoc "Chunk according to plan."
  @type chunk :: %{type: :chunk, plan: Kreuzberg.ChunkPlan.t()}
  @typedoc "Use user-provided chunk overrides."
  @type use_overrides :: %{type: :use_overrides, user_chunks: [map()]}
end
