# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5456918e48a2cc07cb10cd95aded7fa51413630eefade0bce1c73b6ec455577a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkMetadata do
  @moduledoc "Metadata about a chunk's position in the original document."

  defstruct byte_start: 0,
            byte_end: 0,
            token_count: nil,
            chunk_index: 0,
            total_chunks: 0,
            first_page: nil,
            last_page: nil,
            heading_context: nil,
            image_indices: []
end
