# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ChunkPlan do
  @moduledoc "Complete chunking plan for a document."

  @typedoc "Complete chunking plan for a document."
  @type t :: %__MODULE__{
          total_chunks: non_neg_integer(),
          chunks: [map()],
          total_estimated_time_ms: non_neg_integer(),
          use_disk_processing: boolean(),
          reason: String.t() | nil
        }

  defstruct total_chunks: 0,
            chunks: [],
            total_estimated_time_ms: 0,
            use_disk_processing: false,
            reason: :large_file
end
