# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f34bdc006092cdaef9fca23f15cfe31a751a684aac9aaaddef86fd85e754afeb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  @type t :: %__MODULE__{
    citation_count: non_neg_integer(),
    format: String.t() | nil,
    authors: [String.t()],
    year_range: map() | nil,
    dois: [String.t()],
    keywords: [String.t()]
  }

  defstruct citation_count: 0,
            format: nil,
            authors: [],
            year_range: nil,
            dois: [],
            keywords: []
end
