# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationEnrichmentConfig do
  @moduledoc "Classification enrichment knob: how to label the document."

  @typedoc "Classification enrichment knob: how to label the document."
  @type t :: %__MODULE__{
          config: map()
        }

  defstruct config: nil
end
