# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f713f4416362b4f6f3ee08d6db609b56f1d0dc50d623e64e62c3e8d6cb5ad98
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
