# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dfeed1ac37394c7549349c3c76ce0956dcd9d9d523bc0697737adbb65da7eafb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
