# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b8c24e61b1d852d4621fa72d008e0b0fb828f6f5bd8bbff7de983f3944f5b330
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: "",
            has_header: false,
            column_types: []
end
