# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4c8f59385fc0ea427a6fac9fc0bd22c511ffe49eed15e58344ddf42d2ac8980
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @type t :: %__MODULE__{
    name: String.t() | nil,
    field_type: String.t() | nil
  }

  defstruct name: nil,
            field_type: nil
end
