# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f26337600db118280165518835c46a73fabd50615e1417775d4c8e0f10d11a00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  defstruct record_count: 0,
            field_count: 0,
            fields: []
end
