# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bfa539ad44d7a8281f428dafb787ed8cc924d12de64668a69322ae597676733e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @type t :: %__MODULE__{
    mime_type: String.t() | nil,
    filename: String.t() | nil
  }

  defstruct mime_type: nil,
            filename: nil
end
