# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
