# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7351b4d39ff3d7be2e8607325fba027f81f9bf71393cf3c642f53224086d5a7f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  defstruct src: "",
            alt: "",
            title: nil,
            attributes: nil
end
