# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1858285bc9854249bca3bb8d96adc471a98bd78106bb6a964b4e753350983f8b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  defstruct src: "",
            alt: "",
            title: nil,
            attributes: nil
end
