# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e870a0febdec8fb37a0ef4e379e4c108cf18c1f610a096837ef0971a584a65b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocMetadata do
  @moduledoc "Metadata extracted from DOC files."

  defstruct title: "",
            subject: "",
            author: "",
            last_author: "",
            created: "",
            modified: "",
            revision_number: ""
end
