# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7c316294812fa50fbbb4c50667b01b0398910723d0c1845230f7a30618e102cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
