# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7297ec1f376cc0cc4f034cb051f7929e1aa23d1f691978bc64d06d14f6dd7b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
