# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:47fb52afbae51bc515141a1cf039b7c9ed9d7c5a551f088febc4b09748e7ab1e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: "",
            app_properties: "",
            custom_properties: %{}
end
