# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          text: String.t() | nil,
          metadata: map()
        }

  defstruct element_type: :title,
            text: nil,
            metadata: nil
end
