# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:696c087faca1b2c286f4fb202eb6ecec50137f58069d72f925e73264be4bc4e1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
