# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: map() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
