# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:949a13b22d0b1a5fa2ebe20f744b8f2097f6f32afa830776d4420deb3553e568
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @type t :: %__MODULE__{
    msg_fallback_codepage: non_neg_integer() | nil
  }

  defstruct msg_fallback_codepage: nil
end
