# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd618eede9bfb4c2417bfb037a72712fa7d5717fb43f0f13153adbcd960ac4dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  defstruct msg_fallback_codepage: 0
end
