# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3cd7fb1fac4f8d09dbd38f146d1dcba4a017e30652bd498fbbd82fd5085c412d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
