# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:70e8cd0b3be96805ab1fe1d52f1e14a3958d60e9f8e8e4eeb0b58564c96d30fb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
