# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:506ef1cc1fd70f32920a65fc0ecb671f4904d9cd7cdc7692b93a93cb404b5ea6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
