# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bffb1beec32f7187a563994c2f5d7cbcb342b847b51029eeff5b25220267f9c0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
