# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:663976cb3ba32b2ed6d9176373f6cae83ba5cde06492aeff9aae116e1177141f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedResponse do
  @moduledoc "Embedding response containing generated embeddings."

  defstruct embeddings: [],
            model: "",
            dimensions: 0,
            count: 0
end
