# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93ee60800c26edf40dba618f284019545ed22095ca1339df16ed36e41f630a6d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
