# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c6f8f01fa4e7379264182482199b5c0386cf3b94db26d9ffbea047859737dfb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
