# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62eca958d76784438f9ab0ea471e40f7328e56df7592bff18685fba4d0f3a68d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedResponse do
  @moduledoc "Embedding response containing generated embeddings."

  defstruct embeddings: [],
            model: "",
            dimensions: 0,
            count: 0
end
