# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd7f87e789a8c14cb2795db72837b07fec2302c013b04920b77f8a635b21b430
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
