# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:175099409be9e0e067cd8a9396814591d50df0930b5f51e512b3dd57427f1c44
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
