# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bfef3263b3408cbd20a633f7d1c746f6ea861f64f02743645328d5f57f964db6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  @typedoc "EPUB metadata (Dublin Core extensions)."
  @type t :: %__MODULE__{
          coverage: String.t() | nil,
          dc_format: String.t() | nil,
          relation: String.t() | nil,
          source: String.t() | nil,
          dc_type: String.t() | nil,
          cover_image: String.t() | nil
        }

  defstruct coverage: nil,
            dc_format: nil,
            relation: nil,
            source: nil,
            dc_type: nil,
            cover_image: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
