# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b49789afeab3cbb5e7029a9727c95dc2c5c7ed54cd7236875f4a2c847aa5dfbc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelSheet do
  @moduledoc "Single Excel worksheet."

  defstruct name: "",
            markdown: "",
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
