# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map(),
          revisions: [map()] | nil
        }

  defstruct sheets: [],
            metadata: %{},
            revisions: nil
end
