# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:617ed9c056af8f5bd668f0577471ec6973c3e17e6377a013d7c809fa0cdc6845
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExecutionProviderType do
  @moduledoc "ONNX Runtime execution provider type."

  @type t :: :auto | :cpu | :core_ml | :cuda | :tensor_rt

  @auto :auto
  @cpu :cpu
  @core_ml :core_ml
  @cuda :cuda
  @tensor_rt :tensor_rt

  @spec auto() :: t()
  def auto, do: @auto
  @spec cpu() :: t()
  def cpu, do: @cpu
  @spec core_ml() :: t()
  def core_ml, do: @core_ml
  @spec cuda() :: t()
  def cuda, do: @cuda
  @spec tensor_rt() :: t()
  def tensor_rt, do: @tensor_rt
end
