# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImage do
  @moduledoc "Extracted image from a document."

  defstruct data: "",
            format: "",
            image_index: 0,
            page_number: nil,
            width: nil,
            height: nil,
            colorspace: nil,
            bits_per_component: nil,
            is_mask: false,
            description: nil,
            ocr_result: nil,
            bounding_box: nil,
            source_path: nil
end
