# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e8f57d2fe675bbe52c23d1a243ce8da907366d2d32a8299f3eb8f0ca9d28e38
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedInlineImage do
  @moduledoc "Extracted inline image with metadata."

  defstruct data: "",
            format: "",
            filename: nil,
            description: nil,
            dimensions: nil,
            attributes: []
end
