# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
          genres: [String.t()],
          sequences: [String.t()],
          annotation: String.t() | nil
        }

  defstruct genres: [],
            sequences: [],
            annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
