# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FileExtractionConfig do
  @moduledoc "Per-file extraction configuration overrides for batch processing."

  defstruct enable_quality_processing: false,
            ocr: nil,
            force_ocr: false,
            force_ocr_pages: [],
            disable_ocr: false,
            chunking: nil,
            content_filter: nil,
            images: nil,
            pdf_options: nil,
            token_reduction: nil,
            language_detection: nil,
            pages: nil,
            postprocessor: nil,
            html_options: "",
            result_format: "",
            output_format: "",
            include_document_structure: false,
            layout: nil,
            timeout_secs: 0,
            tree_sitter: nil,
            structured_extraction: nil
end
