# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [map()]
        }

  defstruct label: nil,
            content: []
end
