# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d33cfed5e8b4a872a2a3e7769889bc7bf4747297ddc62292c8ca0c8ac73512aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
