# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69999be9c272c5ea97e91f9cb5284c6d81aed5ddd67133adc2dc2ffa2d67ca2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
          block_type: String.t() | nil,
          level: non_neg_integer() | nil,
          inline_content: [map()],
          language: String.t() | nil,
          code: String.t() | nil,
          children: [map()]
        }

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            language: nil,
            code: nil,
            children: []
end
