# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Formula do
  @moduledoc """
  A mathematical formula detected and recognized in a document.

  Populated by the layout-guided formula pipeline: regions classified as
  `LayoutClass::Formula` are routed to the formula OCR task, which returns the
  LaTeX source for the region. The field is always present on
  [`ExtractionResult`](super::extraction::ExtractionResult) but only populated
  when the `layout-detection` feature is active and the document contains
  formula regions.
  """

  @typedoc "A mathematical formula detected and recognized in a document."
  @type t :: %__MODULE__{
          latex: String.t() | nil,
          bbox: map(),
          page: non_neg_integer()
        }

  defstruct latex: nil,
            bbox: nil,
            page: 0
end
