# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da508a958ffc99e94d5891617bc3717e3066c9a34c9a7cb5d99219f99d68a862
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
