# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:140e629c96533e06324d24b6da36ce7a5ff719ada8c416fe5e9f9a367e0003c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
