# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cdfb89a5a4bdf1fd2948b157886075c2673b0c9bcdda17c3d7273d240694c640
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
