# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fed71540df3e2432489c7a8d00f100d237a1a398c85333ca54a4df5b086fc24c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
