# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b6bba97bfed18918f3e90f32de2371002da2a5156ac2e6e1fd893ab45d06a92e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderFooter do
  @moduledoc false

  defstruct paragraphs: [],
            tables: [],
            header_type: ""
end
