# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:26f20d8b9bb5f2c6eaa3830e023b73c2f5b48828aefb6734d1dd28bea8ece726
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
