# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1a3f5000572b2e79ec493b20b30f90adadc31f38a2db6fea2d212c2116bcb22
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
