# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1615c8f5e45305c6327123993fbe8e86bbf53674b981c65f2258ec8ffe7ce8c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlMetadata do
  @moduledoc "HTML metadata extracted from HTML documents."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{},
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
