# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageExtractionConfig do
  @moduledoc "Image extraction configuration."

  defstruct extract_images: false,
            target_dpi: 0,
            max_image_dimension: 0,
            inject_placeholders: false,
            auto_adjust_dpi: false,
            min_dpi: 0,
            max_dpi: 0,
            max_images_per_page: 0
end
