# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:84e1de0f2987d791eb8f1e6a48f5044f09c0e6f0cf5cf28085dd25a9e2a4ac8e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
