# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          image_type: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            image_type: :data_uri
end
