# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f364c832d2130c790aafc8eadc321362a8618e57a337ed53e9c820a983730509
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: "",
            yake_params: nil,
            rake_params: nil
end
