# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:423e7923485d66a45c541f6aa1131dd0bf4133712f215075cf3a3d9b376fd99a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          score: float(),
          algorithm: String.t() | nil,
          positions: [non_neg_integer()] | nil
        }

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
