# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:143bddfc147b84f9f5f45bf1af6b3be24fc7964b609c4508e0dab8964d038f5a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: "",
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
