# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:adeda84bb72f0795dea340ef72ccde24864a364692cc796de0980ab1300c855b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
