# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:761e5ccb329b09a02b4f208ce59bbe97c82d8d56c931243fb99693c40ec40a26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: String.t() | nil,
          confidence: float(),
          bbox: map()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
