# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7dfe7894a9d220f29ed7ab15879b5bbab678030d73c7f6b73d6a706d0cefc523
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @type t :: %__MODULE__{
    class_name: String.t() | nil,
    confidence: float(),
    bbox: map()
  }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
