# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:340add03a24023f184e661ecf4b258cbd0900d6dabdd819541e5c19976ecd8d8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.LinkType do
  @moduledoc "Link type classification."

  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @spec anchor() :: t()
  def anchor, do: @anchor
  @spec internal() :: t()
  def internal, do: @internal
  @spec external() :: t()
  def external, do: @external
  @spec email() :: t()
  def email, do: @email
  @spec phone() :: t()
  def phone, do: @phone
  @spec other() :: t()
  def other, do: @other
end
