# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:369a2039995e1785dbd9dc3c6c4bf778ad29b6ed80c62de7ce7313d8c6f50184
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
