# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e53d42a5ab41caf9ea1ab5c712c3810204eed5efb028eafa4faf702fcf19c160
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
