# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6447fc10b0dcfa63b1748a56fc2f1376443df17ef49d78831d8f0de6f966c8ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Note do
  @moduledoc false

  defstruct id: "",
            note_type: "",
            paragraphs: []
end
