# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78f2c3287b3ad3fa3ddf094d09cfe1a97e2df74eef2c106e5649cb7d21bd3829
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc "Table detected via OCR."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: nil
end
