# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5fa43a074a7939fcfba98741b18a54eb5aea48255c846440bbbad0daa07ef449
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
