# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f7dcbb2003e72322701930b476b7f62cb542fdb7d54354ce5265024e4369159
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried.
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
          stages: [map()],
          quality_thresholds: map()
        }

  defstruct stages: [],
            quality_thresholds: nil
end
