# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f95f51e05629149acd18a65b709920fc5a4ae7e44efd03f839e5a0414b1bb888
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  defstruct angle_degrees: 0.0,
            confidence: nil
end
