# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:691657b0de6f4830e57c71ec300ed11152baef20b9566bca5ce46b920e57774b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OpenWebDocumentResponse do
  @moduledoc "OpenWebUI \"External\" engine response format."

  defstruct page_content: "",
            metadata: ""
end
