# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1e6eb8bc9ad7d4463dc054b677765e826d1ea875aa1bb103845d322df7fab8f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc "Type of paginated unit in a document."

  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @spec page() :: t()
  def page, do: @page
  @spec slide() :: t()
  def slide, do: @slide
  @spec sheet() :: t()
  def sheet, do: @sheet
end
