# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:64fc5b395d2bd1a767e4057df2f880044946ae6251455f10289946891e2c4d4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageMarginsPoints do
  @moduledoc "Page margins converted to points (1/72 inch)."

  defstruct top: 0.0,
            right: 0.0,
            bottom: 0.0,
            left: 0.0,
            header: 0.0,
            footer: 0.0,
            gutter: 0.0
end
