# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df949a23ed01418d22789527e8549214dbbbfc9722e5d867b5312dbc59a47aff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageInfo do
  @moduledoc """
  Metadata for individual page/slide/sheet.

  Captures per-page information including dimensions, content counts,
  and visibility state (for presentations).
  """

  @typedoc "Metadata for individual page/slide/sheet."
  @type t :: %__MODULE__{
          number: non_neg_integer(),
          title: String.t() | nil,
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil,
          hidden: boolean() | nil,
          is_blank: boolean() | nil,
          has_vector_graphics: boolean()
        }

  defstruct number: 0,
            title: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
