# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3f82325dfe43ee4bc1ad26a60248c67350a92597e314e563f214e96066c67e3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
