# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ccc55c7acc5023d6df9734b9624de85c5e87e3470759704f4e69f85e4205bb66
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc "Type of paginated unit in a document."

  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @spec page() :: t()
  def page, do: @page
  @spec slide() :: t()
  def slide, do: @slide
  @spec sheet() :: t()
  def sheet, do: @sheet
end
