# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d43055ee5a0022a3445a9043f10a6d3130a8021b76eb1df286d15a9fd1aa38a1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.PdfMetadata do
  @moduledoc "PDF-specific metadata."

  defstruct pdf_version: "",
            producer: "",
            is_encrypted: false,
            width: 0,
            height: 0,
            page_count: 0
end
