# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d2ec0b895824c12d50a73abcafd51730f5046eeacf5cb0cd596abfd1d3583c02
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
