# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionFinding do
  @moduledoc "One redaction event: which span was rewritten, why, and with what."

  @typedoc "One redaction event: which span was rewritten, why, and with what."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: String.t() | nil,
          strategy: String.t() | nil,
          replacement_token: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            strategy: :mask,
            replacement_token: nil
end
