# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionFinding do
  @moduledoc "One redaction event: which span was rewritten, why, and with what."

  @typedoc "One redaction event: which span was rewritten, why, and with what."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: String.t() | nil,
          strategy: String.t() | nil,
          replacement_token: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            strategy: :mask,
            replacement_token: nil
end
