# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a47e9403195e17eb96c9fb33571662840df1e41fa5876c49414e2103ea80a7af
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RerankerModelType do
  @moduledoc """
  Reranker model types supported by Kreuzberg.

  Since v5.0.0.
  """

  @typedoc "Reranker model types supported by Kreuzberg."
  @type t :: term()

  @typedoc "Use a preset cross-encoder model (recommended)."
  @type preset :: %{type: :preset, name: String.t()}
  @typedoc "Use a custom ONNX cross-encoder from HuggingFace."
  @type custom :: %{type: :custom, model_id: String.t(), model_file: String.t(), additional_files: [String.t()], max_length: integer()}
  @typedoc "Provider-hosted reranker via liter-llm (e.g. Cohere, Jina, Voyage)."
  @type llm :: %{type: :llm, llm: Kreuzberg.LlmConfig.t()}
  @typedoc "In-process reranker registered via the plugin system."
  @type plugin :: %{type: :plugin, name: String.t()}
end
