# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c21900d82dc561e2073e55f9e7df5b8246ebf4a34c19f0032ffef38f36dba5b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.StreamReader do
  @moduledoc false

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
