# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredInput do
  @moduledoc """
  Signals consumed by the call-mode heuristic.

  All fields derive from a prior kreuzberg extraction — no double-work.
  This is a plain DTO; it intentionally has no dependency on internal
  kreuzberg extraction types so it can be constructed from any source.
  """

  @typedoc "Signals consumed by the call-mode heuristic."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          page_count: non_neg_integer(),
          text_coverage: float(),
          avg_chars_per_page: float(),
          embedded_image_count: non_neg_integer(),
          user_force_vision: boolean()
        }

  defstruct mime_type: nil,
            page_count: 0,
            text_coverage: 0.0,
            avg_chars_per_page: 0.0,
            embedded_image_count: 0,
            user_force_vision: false
end
