# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:92152e444367313d22c4788ac4087c2757f0b99b1d6c20cb74aa90083c0fef19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @typedoc "Structured data type classification."
  @type t :: :"json-ld" | :microdata | :rdfa

  @json_ld :"json-ld"
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD structured data"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "Microdata"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDFa"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
