# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:51cf70f05cf9dfd0ff8ac3a2a9dcc443d0a0691e4c597ff7f85eccaa5b641809
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
