# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:321ab6ed7e8578e1e62017c4a52276f518cb14f09707c77ba5cb943115a68b4c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StyleDefinition do
  @moduledoc "A single style definition parsed from `<w:style>` in `word/styles.xml`."

  defstruct id: "",
            name: nil,
            style_type: "",
            based_on: nil,
            next_style: nil,
            is_default: false,
            paragraph_properties: "",
            run_properties: ""
end
