# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c21efd8aa25f3afe74c7f4ed214e8b6b8efbd2fd84bf4c0c514acffaee9ef8a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableCell do
  @moduledoc "Individual table cell with content and optional styling."

  defstruct content: "",
            row_span: 0,
            col_span: 0,
            is_header: false
end
