# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7ce4dd70dc806ef45fca3f3ce428175cb277f23e1d740dd75d73112d3248525
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableCell do
  @moduledoc "Individual table cell with content and optional styling."

  defstruct content: "",
            row_span: 0,
            col_span: 0,
            is_header: false
end
