# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [map()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
