# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d47448fdb9cbf04cde9505102ee13e059b0cf5e0f1ebb435a81eb9bebfd09a21
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
