# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:761e5ccb329b09a02b4f208ce59bbe97c82d8d56c931243fb99693c40ec40a26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Kreuzberg.Native
  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_default()}
  end
  def default() do
    ref = Native.tokencounter_default()
    %__MODULE__{ref: ref}
  end
end
