# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          preserve_important_words: boolean()
        }

  defstruct mode: nil,
            preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
