# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f1c80bd6bc3b3364992d73a5c2f99e0a2e8f016704844db171362402ae2efe6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.TracingLayer do
  @moduledoc "A [`tower::Layer`] that wraps each extraction in a semantic tracing span."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tracinglayer_default()}
  end
end
