# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0eb06e6e0799425c52a8c3258bf752718db7bdeb72f5b8d56833b3317d037116
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc "A URI extracted from a document."

  defstruct url: "",
            label: nil,
            page: nil,
            kind: :hyperlink
end
