# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f1c34728d3217e997107800517c61d03e2ad93027119a3d2523cf18dc83e076
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule Kreuzberg.UriKind do
  @moduledoc "Semantic classification of an extracted URI."

  @type t :: :hyperlink | :image | :anchor | :citation | :reference | :email

  @hyperlink :hyperlink
  @image :image
  @anchor :anchor
  @citation :citation
  @reference :reference
  @email :email

  @spec hyperlink() :: t()
  def hyperlink, do: @hyperlink
  @spec image() :: t()
  def image, do: @image
  @spec anchor() :: t()
  def anchor, do: @anchor
  @spec citation() :: t()
  def citation, do: @citation
  @spec reference() :: t()
  def reference, do: @reference
  @spec email() :: t()
  def email, do: @email
end
