# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67386ccba3249a77d2593960b208cfaf1ba8f08fff71077e29857c18df454479
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmRequest do
  @moduledoc "Cache warm request."

  defstruct all_embeddings: false,
            embedding_model: ""
end
