# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bd31e0036d504f8b69c6d3602772932741421cfbef9c8b096dd13bb1cd936d8e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XlsxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for XLSX"

  defstruct application: "",
            app_version: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false,
            company: "",
            worksheet_names: []
end
