# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3a2066bbb5be62e6237a2bcdd35fa7b9cfe32012f94a4f6091d3e479c659dea
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
