# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:423e7923485d66a45c541f6aa1131dd0bf4133712f215075cf3a3d9b376fd99a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.XmlMetadata do
  @moduledoc """
  XML metadata extracted during XML parsing.

  Provides statistics about XML document structure.
  """

  @typedoc "XML metadata extracted during XML parsing."
  @type t :: %__MODULE__{
          element_count: non_neg_integer(),
          unique_elements: [String.t()]
        }

  defstruct element_count: 0,
            unique_elements: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
