# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:423e7923485d66a45c541f6aa1131dd0bf4133712f215075cf3a3d9b376fd99a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
