# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d43dc21104f64d4e3426132ea24338453b27b789258623903f2be608dfc17425
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
