# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56a69764e3c069a640da6e3c94f03d49872d1095fd28eb02575845ab4d56208f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
