// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:302fa3ea50c3cf1dd5b15a09c908990ea03d0228198664d5cad11a1bf925ebcc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Semantic element extracted from document.
 *
 * Represents a logical unit of content with semantic classification,
 * unique identifier, and metadata for tracking origin and position.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Element(
    @JsonProperty("element_id") String elementId,
    @JsonProperty("element_type") ElementType elementType,
    String text,
    ElementMetadata metadata
) {

    /**
     * Parse a {@code Element} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static Element fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, Element.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse Element from JSON: " + e.getMessage(), e);
        }
    }
}
