// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:24ed936e0cdd67d987f1339929cbe47d3cb07c1aeb688c0ac6cf26cf6bf2b8c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Language detection configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class LanguageDetectionConfigBuilder {

    @JsonProperty("enabled")
    private boolean enabled = true;
    @JsonProperty("min_confidence")
    private double minConfidence = 0.0;
    @JsonProperty("detect_multiple")
    private boolean detectMultiple = false;

    /** Sets the enabled field. */
    @JsonProperty("enabled")
    public LanguageDetectionConfigBuilder withEnabled(final boolean value) {
        this.enabled = value;
        return this;
    }

    /** Sets the minConfidence field. */
    @JsonProperty("min_confidence")
    public LanguageDetectionConfigBuilder withMinConfidence(final double value) {
        this.minConfidence = value;
        return this;
    }

    /** Sets the detectMultiple field. */
    @JsonProperty("detect_multiple")
    public LanguageDetectionConfigBuilder withDetectMultiple(final boolean value) {
        this.detectMultiple = value;
        return this;
    }

    /** Builds the LanguageDetectionConfig instance. */
    public LanguageDetectionConfig build() {
        return new LanguageDetectionConfig(
            enabled,
            minConfidence,
            detectMultiple
        );
    }
}
