// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4afd295979b15dbd5b86230489d736255f4ad359accb6ba68ebcf08c29e78eba
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum ReductionLevel {
    Off("off"),
    Light("light"),
    Moderate("moderate"),
    Aggressive("aggressive"),
    Maximum("maximum");

    /** The string value. */
    private final String value;

    ReductionLevel(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ReductionLevel fromValue(final String value) {
        for (ReductionLevel e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
