// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Image {
    public class ImageTests
    {
        [Fact]
        public void ImageMetadataOnly()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("images/example.jpg");
            var result = TestHelpers.RunExtraction("images/example.jpg", "{\"ocr\":null}");
            TestHelpers.AssertExpectedMime(result, new[] { "image/jpeg" });
            TestHelpers.AssertMaxContentLength(result, 100);
        }

    }
}
