// DO NOT EDIT - auto-generated by alef
// alef:hash:3e9750349b7aeaefee4dc21b4616209b660931a3204927feb49e14ec77cbd152
package io.xberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TranscriptionException with the given message. */
  public TranscriptionException(final String message) {
    super(message);
  }

  /** Creates a new TranscriptionException with the given message and cause. */
  public TranscriptionException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
