// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, list_document_extractors } from 'kreuzberg';

describe('document_extractor_management', () => {
  it('extractors_clear: Clear all document extractors and verify list is empty', async () => {
    const result = await extract_file('');
    expect(result.result.trim()).toHaveLength(0);
  });

  it('extractors_list: List all registered document extractors', () => {
    list_document_extractors({ setup: { lazy_init_required: { init_action: "extract_file_sync", init_data: { create_temp_file: true, temp_file_content: "%PDF-1.4\n%EOF\n", temp_file_name: "test.pdf" }, languages: ["go"] } } });
  });

  it('extractors_unregister: Unregister nonexistent document extractor gracefully', async () => {
    await extract_file('');
  });
});
