// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:13931cdefb609807f63e790eb7c6c6624a88e55eaf4e7cc137f2c4e70ce0f95f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { extractFile, renderPdfPageToPng, type WasmExtractionConfig } from 'kreuzberg';

describe('error', () => {
  it('error_file_not_found_async: Error when file does not exist (async)', async () => {
    await expect(async () => {
      await extractFile("nonexistent/file.pdf", undefined, {} as unknown as WasmExtractionConfig);
    }).rejects.toThrow();
  });

  it('error_render_corrupt_pdf: Error when rendering page from corrupt PDF', async () => {
    await expect(async () => {
      const pdf_bytesBytes = readFileSync("pdf/corrupt_truncated.pdf");
      await renderPdfPageToPng(pdf_bytesBytes, 0);
    }).rejects.toThrow();
  });

  it('error_render_invalid_page: Error when rendering page number exceeds document page count', async () => {
    await expect(async () => {
      const pdf_bytesBytes = readFileSync("pdf/fake_memo.pdf");
      await renderPdfPageToPng(pdf_bytesBytes, 0);
    }).rejects.toThrow();
  });
});
