// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file } from 'kreuzberg';

describe('html', () => {
  it('html_complex_layout: Large Wikipedia HTML page to validate complex conversion.', async () => {
    const result = await extract_file("html/taylor_swift.html");
    expect(result.mimeType.trim()).toBe("text/html");
    expect(result.content.length).toBeGreaterThanOrEqual(1000);
  });

  it('html_simple_table: HTML table converted to markdown should retain structure.', async () => {
    const result = await extract_file("html/simple_table.html");
    expect(result.mimeType.trim()).toBe("text/html");
    expect(result.content.length).toBeGreaterThanOrEqual(100);
    expect(result.content).toContain("Product");
    expect(result.content).toContain("Category");
    expect(result.content).toContain("Price");
    expect(result.content).toContain("Stock");
    expect(result.content).toContain("Laptop");
    expect(result.content).toContain("Electronics");
    expect(result.content).toContain("Sample Data Table");
  });
});
