// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5abc98e74457171a85425bb87248346aadecb9f2a4e21ff6244124173178eae2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, listExtractors, listOcrBackends, listPostProcessors, listValidators } from 'kreuzberg';

describe('registry', () => {
  it('list_document_extractors: List document extractors', () => {
    listExtractors();
  });

  it('list_ocr_backends: List OCR backends', () => {
    listOcrBackends();
  });

  it('list_post_processors: List post-processors', () => {
    listPostProcessors();
  });

  it('list_validators: List validators', () => {
    listValidators();
  });
});
