// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:79c4a1eec325d77f482da676b3db5b7b64c87ef9a8344f08ddef4d2a9e774851
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, extract_file_to_json, extract_file_to_toon, WasmExtractionConfig } from 'kreuzberg';

describe('serialization', () => {
  it('serialize_json_basic: Serialize extraction result to JSON', () => {
    const options = new WasmExtractionConfig();
    const result = extract_file_to_json("test_documents/text/plain.txt", options);
    expect(result.content.length).toBeGreaterThanOrEqual(1);
  });

  it('serialize_json_pdf: Serialize PDF extraction to JSON', () => {
    const options = new WasmExtractionConfig();
    const result = extract_file_to_json("test_documents/pdf/sample.pdf", options);
    expect(result.content).toContain("content");
  });

  it('serialize_toon_basic: Serialize extraction result to TOON format', () => {
    const options = new WasmExtractionConfig();
    const result = extract_file_to_toon("test_documents/text/plain.txt", options);
    expect(result.content.length).toBeGreaterThanOrEqual(1);
  });

  it('serialize_toon_pdf: Serialize PDF extraction to TOON', () => {
    const options = new WasmExtractionConfig();
    const result = extract_file_to_toon("test_documents/pdf/sample.pdf", options);
    expect(result.content.length).toBeGreaterThanOrEqual(10);
  });
});
