// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:13e489e9f8319a32c437eb44af32d239ea38f866f99563cccd557b5e05e30167
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, it, expect } from 'vitest';
import { extract_file, extract_file_sync, WasmExtractionConfig } from 'kreuzberg';

describe('table', () => {
  it('table_csv_extraction: CSV file extraction produces content', () => {
    const result = extract_file_sync("csv/stanley_cups.csv");
    expect(result.content.length).toBeGreaterThanOrEqual(10);
  });

  it('table_html_extraction: HTML table extraction produces markdown format', () => {
    const options = new WasmExtractionConfig();
    options.outputFormat = "markdown";
    const result = extract_file_sync("html/simple_table.html", options);
    expect(["|"].some((v) => result.content.includes(v))).toBe(true);
  });

  it('table_xlsx_markdown: XLSX extraction produces markdown table format', () => {
    const options = new WasmExtractionConfig();
    options.outputFormat = "markdown";
    const result = extract_file_sync("xlsx/stanley_cups.xlsx", options);
    expect(["|", "---"].some((v) => result.content.includes(v))).toBe(true);
  });
});
