# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9bb18d8ed8abffcda244f6646c41a7a37d3f94fb353e922b682cbb49f1f49f72
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'embedding_backend_management' do
  it 'embedding_backends_clear: Clear all embedding backends and verify list is empty' do
    Kreuzberg.clear_embedding_backends()

  end

  it 'embedding_backends_list: List all registered embedding backends' do
    result = Kreuzberg.list_embedding_backends()

    expect(result).not_to be_nil
  end
end
