# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d198d4032ff3ac0b71ad30266fe09b7aba8a7a6d8c950808017e0eea36140090
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'hash' do
  it 'blake3_bytes_pdf: Hash PDF bytes using BLAKE3' do
    result = Kreuzberg.blake3_hash_bytes('pdf/fake_memo.pdf')
    expect(result.length).to be >= 64
  end

  it 'blake3_bytes_text: Hash text file bytes using BLAKE3' do
    result = Kreuzberg.blake3_hash_bytes('text/plain.txt')
    expect(result.length).to be >= 64
  end

  it 'blake3_file_not_found: blake3_hash_file nonexistent file' do
    expect { Kreuzberg.blake3_hash_file('nonexistent/file.pdf') }.to raise_error
  end

  it 'blake3_file_pdf: Hash PDF file using BLAKE3' do
    result = Kreuzberg.blake3_hash_file('pdf/fake_memo.pdf')
    expect(result.length).to be >= 64
  end

  it 'blake3_file_text: Hash text file using BLAKE3' do
    result = Kreuzberg.blake3_hash_file('text/plain.txt')
    expect(result.length).to be >= 64
  end

  it 'compute_hash_basic: Compute hash for PDF file' do
    result = Kreuzberg.compute_hash('pdf/fake_memo.pdf')
    expect(result).not_to be_nil
  end

  it 'compute_hash_different: Hash different content' do
    result = Kreuzberg.compute_hash('different content')
    expect(result).not_to be_nil
  end

  it 'fast_hash_basic: Hash PDF file using fast hash' do
    result = Kreuzberg.fast_hash('pdf/fake_memo.pdf')
    expect(result).not_to be_nil
  end

  it 'fast_hash_empty: Hash empty bytes' do
    result = Kreuzberg.fast_hash('')
    expect(result).not_to be_nil
  end
end
