# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea147fc34b3dfdd2a32516c72ea0b097efe4fed03d90f75b23d8c9fd1363a3c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'post_processor_management' do
  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    Kreuzberg.clear_post_processors()

  end

  it 'post_processors_list: List all registered post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end
end
