# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'registry_operations' do
  it 'extensions_docx: Get file extensions for DOCX MIME type' do
    result = Kreuzberg.get_extensions_for_mime('application/vnd.openxmlformats-officedocument.wordprocessingml.document')

    expect(result).not_to be_nil
  end

  it 'extensions_html: Get file extensions for HTML MIME type' do
    result = Kreuzberg.get_extensions_for_mime('text/html')

    expect(result).not_to be_nil
  end

  it 'extensions_pdf: Get file extensions for PDF MIME type' do
    result = Kreuzberg.get_extensions_for_mime('application/pdf')

    expect(result).not_to be_nil
  end
end
