# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b9dd1e402f639a0c40b915fe84f4f72b62cf0eb949e1bbcce04a07b2d06d1ca4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'registry_operations' do
  it 'extensions_docx: Get file extensions for DOCX MIME type' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end

  it 'extensions_html: Get file extensions for HTML MIME type' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end

  it 'extensions_pdf: Get file extensions for PDF MIME type' do
    result = Kreuzberg.get_extensions_for_mime('')
    expect(result.result.to_s).to include('pdf')
  end

  it 'list_formats_all: List all supported formats and their extensions' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end
end
