# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:967e144c67407b9bc8ea7490bcab22792aa24ef81e86941f8ba94eee1551107b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'rerank' do
  it 'rerank_basic: rerank: basic plugin-based reranking with registered mock backend' do
    result = Kreuzberg.rerank_async('What is machine learning?', ['Machine learning is a subset of artificial intelligence focused on learning from data.', 'Cats are independent animals that prefer to play alone.', 'Deep learning uses neural networks with multiple layers.'], {model: { 'name' => 'rerank_basic', 'type' => 'plugin' }})

    expect(result).not_to be_nil
  end

  it 'rerank_empty_documents: rerank: empty documents list returns empty result' do
    result = Kreuzberg.rerank_async('test query', [], {model: { 'name' => 'rerank_empty_documents', 'type' => 'plugin' }})

    expect(result).not_to be_nil
  end

  it 'rerank_top_k: rerank: top_k truncation to 2 results from 4 documents' do
    result = Kreuzberg.rerank_async('machine learning', ['Machine learning is a subset of artificial intelligence focused on learning from data.', 'Deep learning uses neural networks with multiple layers.', 'Classical statistics predates modern machine learning.', 'Photosynthesis is the process by which plants convert sunlight to energy.'], {model: { 'name' => 'rerank_top_k', 'type' => 'plugin' }, top_k: 2})

    expect(result).not_to be_nil
  end
end
