#!/usr/bin/env bash
# Build Go bindings
# Used by: ci-go.yaml - Build Go bindings step
# Supports: Unix (Linux/macOS)

set -euo pipefail

cd packages/go/v4
workspace="$(cd ../../.. && pwd)"

ffi_path="${workspace}/target/release"
path_sep=":"

if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
	export LD_LIBRARY_PATH="${ffi_path}${path_sep}${LD_LIBRARY_PATH}"
else
	export LD_LIBRARY_PATH="${ffi_path}"
fi

if [[ -n "${DYLD_LIBRARY_PATH:-}" ]]; then
	export DYLD_LIBRARY_PATH="${ffi_path}${path_sep}${DYLD_LIBRARY_PATH}"
else
	export DYLD_LIBRARY_PATH="${ffi_path}"
fi

# Ensure pkg-config can find the dev .pc file generated by crates/kreuzberg-ffi/build.rs
dev_pc_dir="${workspace}/crates/kreuzberg-ffi"
if [[ -n "${PKG_CONFIG_PATH:-}" ]]; then
	export PKG_CONFIG_PATH="${dev_pc_dir}${path_sep}${PKG_CONFIG_PATH}"
else
	export PKG_CONFIG_PATH="${dev_pc_dir}"
fi

# Try build normally first, use -x flag on failure for diagnostics
if ! go build -v ./...; then
	echo ""
	echo "=== Build failed, retrying with verbose CGO diagnostics ==="
	go build -x -v ./...
fi
