// DO NOT EDIT - auto-generated by alef
// alef:hash:172edec9ba85a11ae0aa02f10ae2bbf6e6f717b3dbc8ebf80571d4582c4d5c3f
package dev.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) {
    super(message);
  }

  /** Creates a new HeuristicsErrorException with the given message and cause. */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
