package com.kreuzberg.e2e;

// CHECKSTYLE.OFF: UnusedImports - generated code
// CHECKSTYLE.OFF: LineLength - generated code
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Arrays;
import java.util.Collections;
import org.junit.jupiter.api.Test;

// CHECKSTYLE.ON: UnusedImports
// CHECKSTYLE.ON: LineLength

// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang java

/** Tests for archive fixtures. */
public class ArchiveTest {
  private static final ObjectMapper MAPPER = new ObjectMapper();

  @Test
  public void archiveSevenzBasic() throws Exception {
    JsonNode config = null;
    E2EHelpers.runFixture(
        "archive_sevenz_basic",
        "archives/documents.7z",
        config,
        Collections.emptyList(),
        null,
        true,
        result -> {
          E2EHelpers.Assertions.assertExpectedMime(
              result, Arrays.asList("application/x-7z-compressed"));
          E2EHelpers.Assertions.assertMinContentLength(result, 10);
        });
  }

  @Test
  public void archiveTarBasic() throws Exception {
    JsonNode config = null;
    E2EHelpers.runFixture(
        "archive_tar_basic",
        "archives/documents.tar",
        config,
        Collections.emptyList(),
        null,
        true,
        result -> {
          E2EHelpers.Assertions.assertExpectedMime(
              result, Arrays.asList("application/x-tar", "application/tar"));
          E2EHelpers.Assertions.assertMinContentLength(result, 10);
        });
  }

  @Test
  public void archiveZipBasic() throws Exception {
    JsonNode config = null;
    E2EHelpers.runFixture(
        "archive_zip_basic",
        "archives/documents.zip",
        config,
        Collections.emptyList(),
        null,
        true,
        result -> {
          E2EHelpers.Assertions.assertExpectedMime(
              result, Arrays.asList("application/zip", "application/x-zip-compressed"));
          E2EHelpers.Assertions.assertMinContentLength(result, 10);
        });
  }
}
