// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7196403e5e3db10bc9da8543041828140a9622f46b9aec2f03f5f8e270765031
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';

// E2e tests for category: async
void main() {
  test('extract_bytes empty MIME async', () async {
    final result = await KreuzbergBridge.extractBytes(File('text/plain.txt').readAsBytesSync(), '');
  });

  test('extract_bytes unsupported MIME async', () async {
    final result = await KreuzbergBridge.extractBytes(File('text/plain.txt').readAsBytesSync(), 'application/x-nonexistent');
  });

}
