#!/usr/bin/env php
<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7835d452ab4cc6246c3a04ef7574141c64234bc463175ac96293bb6c56a5a4ba
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

// Determine platform-specific extension suffix.
$extSuffix = match (PHP_OS_FAMILY) {
    'Darwin' => '.dylib',
    default => '.so',
};
$extPath = __DIR__ . '/../../target/release/libkreuzberg_php' . $extSuffix;

// If extension is not already loaded and the extension file exists, we need to
// restart PHP with the extension enabled via command-line.
if (!extension_loaded('kreuzberg_php') && file_exists($extPath)) {
    // Reconstruct the command with the extension flag.
    $php = PHP_BINARY;
    $extFlag = "-d";
    $extVal = "extension=" . $extPath;
    $phpunitPath = __DIR__ . '/vendor/bin/phpunit';

    // Build the full command: php -d extension=... vendor/bin/phpunit [args...]
    $cmd = array_merge(
        [$php, $extFlag, $extVal],
        [$phpunitPath],
        array_slice($GLOBALS['argv'], 1)
    );

    // Execute and exit with the same code.
    passthru(implode(' ', array_map('escapeshellarg', $cmd)), $exitCode);
    exit($exitCode);
}

// Extension is already loaded (either built-in or via this script after restart).
// Invoke PHPUnit normally.
$phpunitPath = __DIR__ . '/vendor/bin/phpunit';
if (!file_exists($phpunitPath)) {
    echo "PHPUnit not found at $phpunitPath. Run 'composer install' first.\n";
    exit(1);
}

require $phpunitPath;
