name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get Dart dependencies
        run: dart pub get --working-dir=packages/dart
      - name: Analyze Dart code
        run: dart analyze packages/dart
      - name: Run tests
        run: dart test --working-dir=packages/dart
