// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:497f5e30567243eeb012c9eed0cd18128e34746d2c4afa3dd6a875c20d0bf31d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: async
package e2e_test

import (
	"os"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_AsyncExtractBytesEmptyMime(t *testing.T) {
	// extract_bytes empty MIME async
	contentBytes, contentBytesErr := os.ReadFile(`text/plain.txt`)
	if contentBytesErr != nil {
		t.Fatalf("read fixture text/plain.txt: %v", contentBytesErr)
	}
	_, err := kreuzberg.ExtractBytes(contentBytes, ``, kreuzberg.ExtractionConfig{})
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}

func Test_AsyncExtractBytesInvalidMime(t *testing.T) {
	// extract_bytes unsupported MIME async
	contentBytes, contentBytesErr := os.ReadFile(`text/plain.txt`)
	if contentBytesErr != nil {
		t.Fatalf("read fixture text/plain.txt: %v", contentBytesErr)
	}
	_, err := kreuzberg.ExtractBytes(contentBytes, `application/x-nonexistent`, kreuzberg.ExtractionConfig{})
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}
