// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: cache_ops
package e2e_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_GenerateCacheKeyComplex(t *testing.T) {
	// Complex cache key
	result, err := kreuzberg.generate_cache_key(`["hash_abc","config_v2","markdown"]`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Result), 5, "expected length >= 5")
}

func Test_ValidateCacheKeyInvalid(t *testing.T) {
	// Invalid cache key
	_, err := kreuzberg.validate_cache_key(``)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}
