// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31dc5a0d898b9f50b1b01b7771b76f553350023f15e9baab503e8c9c334ba8ca
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: code
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_CodeShebangDetection(t *testing.T) {
	// Test language detection from shebang line via bytes input
	mime_typeVal := `text/x-source-code`
	result, err := kreuzberg.ExtractFileSync(`code/script.sh`, &mime_typeVal, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(string(result.MimeType)) != `text/x-source-code` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 10, "expected length >= 10")
	if !strings.Contains(string(result.Content), `build`) {
		t.Errorf("expected to contain %s", `build`)
	}
	if !strings.Contains(string(result.Content), `clean`) {
		t.Errorf("expected to contain %s", `clean`)
	}
}
