// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:006ebe5b111ca50f51a945acd7190757c997c4c5f0d03b7cc01e8a6ba55bb8ec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: image
package e2e_test

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_ImageMetadataOnly(t *testing.T) {
	// JPEG image to validate metadata extraction without OCR.
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}

func Test_ImageSvgBasic(t *testing.T) {
	// SVG image extraction.
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}
