// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:74016185d93e56df699e9282d94f5dd9f07e9ef79d0b01bbbdf2448ddfdeecf4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: registry
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ListDocumentExtractors(t *testing.T) {
	// List document extractors
	_, err := kreuzberg.ListDocumentExtractors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListOcrBackends(t *testing.T) {
	// List OCR backends
	_, err := kreuzberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListPostProcessors(t *testing.T) {
	// List post-processors
	_, err := kreuzberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListValidators(t *testing.T) {
	// List validators
	_, err := kreuzberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
