// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b40c6d6405568a283b1336728bedea8c7f359fc70e7ad937fa32ada73d60e569
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: reranker_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ClearRerankerBackends(t *testing.T) {
	// Clear all reranker backends and verify list is empty
	_ = kreuzberg.ClearRerankerBackends()
}

func Test_ListRerankerBackends(t *testing.T) {
	// List all registered reranker backends
	_, err := kreuzberg.ListRerankerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
