// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a441f72a4eb305a118fbfe845812d0b0fa5e823e67a74fe85b13a951e813996e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: rerank_async_pending
package e2e_test

import (
	"encoding/json"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_AsyncRerank(t *testing.T) {
	// rerank_async: plugin model with no backend registered returns an error
	var documents []string
	if err := json.Unmarshal([]byte(`["Neural networks are a class of machine learning models inspired by biological brains.","The Eiffel Tower is located in Paris.","Convolutional neural networks excel at image recognition tasks."]`), &documents); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	var config kreuzberg.RerankerConfig
	if err := json.Unmarshal([]byte(`{"model":{"name":"async_rerank","type":"plugin"}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := kreuzberg.RerankAsync(`neural networks`, documents, config)
	if err == nil {
		t.Errorf("expected an error, but call succeeded")
	}
}
