// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:32b743ed0535bdcec9ccefbba1c687e77bf811a2185cb8f5f7069ae7796121fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: uri
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ClassifyUriAnchor(t *testing.T) {
	// Classify fragment URI
	_, err := kreuzberg.classify_uri(`#section-header`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ClassifyUriEmail(t *testing.T) {
	// Classify mailto URI
	_, err := kreuzberg.classify_uri(`mailto:user@example.com`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ClassifyUriHttps(t *testing.T) {
	// Classify HTTPS URL
	_, err := kreuzberg.classify_uri(`https://example.com/page`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
