// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdf1e86d14a21c6ee61071588f2f005a3baa5ccd7a378055eb232ca46e473c74
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: uri
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ClassifyUriAnchor(t *testing.T) {
	// Classify fragment URI
	err := kreuzberg.ClassifyURI(`#section-header`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ClassifyUriEmail(t *testing.T) {
	// Classify mailto URI
	err := kreuzberg.ClassifyURI(`mailto:user@example.com`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ClassifyUriHttps(t *testing.T) {
	// Classify HTTPS URL
	err := kreuzberg.ClassifyURI(`https://example.com/page`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
