// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:05623e0e0dd38d5aebf6e2f72056254d3f9c7b7ed090a1610f85c9696fe8b67e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import dev.kreuzberg.ExtractionConfig

/** E2e tests for category: async. */
class AsyncTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testAsyncExtractBytesEmptyMime() = runBlocking {
        // extract_bytes empty MIME async
        val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
        assertFailsWith<Exception> {
            Kreuzberg.extractBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")), "", config)
        }
    }

    @Test
    fun testAsyncExtractBytesInvalidMime() = runBlocking {
        // extract_bytes unsupported MIME async
        val config = MAPPER.readValue("{}", ExtractionConfig::class.java)
        assertFailsWith<Exception> {
            Kreuzberg.extractBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("text/plain.txt")), "application/x-nonexistent", config)
        }
    }

}
