// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:967e144c67407b9bc8ea7490bcab22792aa24ef81e86941f8ba94eee1551107b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import dev.kreuzberg.RerankerConfig

/** E2e tests for category: rerank_async_pending. */
class RerankAsyncPendingTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testAsyncRerank() = runBlocking {
        // rerank_async: basic async reranking with registered mock backend
        val config = MAPPER.readValue("{\"model\":{\"name\":\"async_rerank\",\"type\":\"plugin\"}}", RerankerConfig::class.java)
        val result = Kreuzberg.rerankAsync("neural networks", listOf("Neural networks are a class of machine learning models inspired by biological brains.", "The Eiffel Tower is located in Paris.", "Convolutional neural networks excel at image recognition tasks."), config)
    }

}
